// Code generated by ent, DO NOT EDIT.

package rack

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rack type in the database.
	Label = "rack"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRackNo holds the string denoting the rack_no field in the database.
	FieldRackNo = "rack_no"
	// FieldPositionCode holds the string denoting the position_code field in the database.
	FieldPositionCode = "position_code"
	// FieldRow holds the string denoting the row field in the database.
	FieldRow = "row"
	// FieldColumn holds the string denoting the column field in the database.
	FieldColumn = "column"
	// FieldTotalUnits holds the string denoting the total_units field in the database.
	FieldTotalUnits = "total_units"
	// FieldPowerCapacity holds the string denoting the power_capacity field in the database.
	FieldPowerCapacity = "power_capacity"
	// FieldPowerUsed holds the string denoting the power_used field in the database.
	FieldPowerUsed = "power_used"
	// FieldWeightCapacity holds the string denoting the weight_capacity field in the database.
	FieldWeightCapacity = "weight_capacity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRoom holds the string denoting the room edge name in mutations.
	EdgeRoom = "room"
	// EdgeUnits holds the string denoting the units edge name in mutations.
	EdgeUnits = "units"
	// Table holds the table name of the rack in the database.
	Table = "racks"
	// RoomTable is the table that holds the room relation/edge.
	RoomTable = "racks"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_racks"
	// UnitsTable is the table that holds the units relation/edge.
	UnitsTable = "rack_units"
	// UnitsInverseTable is the table name for the RackUnit entity.
	// It exists in this package in order to avoid circular dependency with the "rackunit" package.
	UnitsInverseTable = "rack_units"
	// UnitsColumn is the table column denoting the units relation/edge.
	UnitsColumn = "rack_units"
)

// Columns holds all SQL columns for rack fields.
var Columns = []string{
	FieldID,
	FieldRackNo,
	FieldPositionCode,
	FieldRow,
	FieldColumn,
	FieldTotalUnits,
	FieldPowerCapacity,
	FieldPowerUsed,
	FieldWeightCapacity,
	FieldStatus,
	FieldPosition,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "racks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"room_racks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// RackNoValidator is a validator for the "rack_no" field. It is called by the builders before save.
	RackNoValidator func(string) error
	// DefaultTotalUnits holds the default value on creation for the "total_units" field.
	DefaultTotalUnits int
	// DefaultPowerUsed holds the default value on creation for the "power_used" field.
	DefaultPowerUsed float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusAvailable is the default value of the Status enum.
const DefaultStatus = StatusAvailable

// Status values.
const (
	StatusAvailable   Status = "available"
	StatusFull        Status = "full"
	StatusMaintenance Status = "maintenance"
	StatusReserved    Status = "reserved"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusFull, StatusMaintenance, StatusReserved:
		return nil
	default:
		return fmt.Errorf("rack: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Rack queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRackNo orders the results by the rack_no field.
func ByRackNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRackNo, opts...).ToFunc()
}

// ByPositionCode orders the results by the position_code field.
func ByPositionCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionCode, opts...).ToFunc()
}

// ByRow orders the results by the row field.
func ByRow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRow, opts...).ToFunc()
}

// ByColumn orders the results by the column field.
func ByColumn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColumn, opts...).ToFunc()
}

// ByTotalUnits orders the results by the total_units field.
func ByTotalUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalUnits, opts...).ToFunc()
}

// ByPowerCapacity orders the results by the power_capacity field.
func ByPowerCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPowerCapacity, opts...).ToFunc()
}

// ByPowerUsed orders the results by the power_used field.
func ByPowerUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPowerUsed, opts...).ToFunc()
}

// ByWeightCapacity orders the results by the weight_capacity field.
func ByWeightCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeightCapacity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRoomField orders the results by room field.
func ByRoomField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoomStep(), sql.OrderByField(field, opts...))
	}
}

// ByUnitsCount orders the results by units count.
func ByUnitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUnitsStep(), opts...)
	}
}

// ByUnits orders the results by units terms.
func ByUnits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRoomStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoomInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
	)
}
func newUnitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UnitsTable, UnitsColumn),
	)
}
