// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldRealName holds the string denoting the real_name field in the database.
	FieldRealName = "real_name"
	// FieldDepartment holds the string denoting the department field in the database.
	FieldDepartment = "department"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRoles holds the string denoting the roles edge name in mutations.
	EdgeRoles = "roles"
	// EdgeCreatedPurchaseOrders holds the string denoting the created_purchase_orders edge name in mutations.
	EdgeCreatedPurchaseOrders = "created_purchase_orders"
	// EdgeInventoryRecords holds the string denoting the inventory_records edge name in mutations.
	EdgeInventoryRecords = "inventory_records"
	// EdgeInitiatedApprovals holds the string denoting the initiated_approvals edge name in mutations.
	EdgeInitiatedApprovals = "initiated_approvals"
	// EdgeRepairTickets holds the string denoting the repair_tickets edge name in mutations.
	EdgeRepairTickets = "repair_tickets"
	// Table holds the table name of the user in the database.
	Table = "users"
	// RolesTable is the table that holds the roles relation/edge. The primary key declared below.
	RolesTable = "user_roles"
	// RolesInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RolesInverseTable = "roles"
	// CreatedPurchaseOrdersTable is the table that holds the created_purchase_orders relation/edge.
	CreatedPurchaseOrdersTable = "purchase_orders"
	// CreatedPurchaseOrdersInverseTable is the table name for the PurchaseOrder entity.
	// It exists in this package in order to avoid circular dependency with the "purchaseorder" package.
	CreatedPurchaseOrdersInverseTable = "purchase_orders"
	// CreatedPurchaseOrdersColumn is the table column denoting the created_purchase_orders relation/edge.
	CreatedPurchaseOrdersColumn = "user_created_purchase_orders"
	// InventoryRecordsTable is the table that holds the inventory_records relation/edge.
	InventoryRecordsTable = "inventory_records"
	// InventoryRecordsInverseTable is the table name for the InventoryRecord entity.
	// It exists in this package in order to avoid circular dependency with the "inventoryrecord" package.
	InventoryRecordsInverseTable = "inventory_records"
	// InventoryRecordsColumn is the table column denoting the inventory_records relation/edge.
	InventoryRecordsColumn = "user_inventory_records"
	// InitiatedApprovalsTable is the table that holds the initiated_approvals relation/edge.
	InitiatedApprovalsTable = "approvals"
	// InitiatedApprovalsInverseTable is the table name for the Approval entity.
	// It exists in this package in order to avoid circular dependency with the "approval" package.
	InitiatedApprovalsInverseTable = "approvals"
	// InitiatedApprovalsColumn is the table column denoting the initiated_approvals relation/edge.
	InitiatedApprovalsColumn = "user_initiated_approvals"
	// RepairTicketsTable is the table that holds the repair_tickets relation/edge.
	RepairTicketsTable = "repair_tickets"
	// RepairTicketsInverseTable is the table name for the RepairTicket entity.
	// It exists in this package in order to avoid circular dependency with the "repairticket" package.
	RepairTicketsInverseTable = "repair_tickets"
	// RepairTicketsColumn is the table column denoting the repair_tickets relation/edge.
	RepairTicketsColumn = "user_repair_tickets"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPassword,
	FieldEmail,
	FieldPhone,
	FieldRealName,
	FieldDepartment,
	FieldStatus,
	FieldLastLoginAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// RolesPrimaryKey and RolesColumn2 are the table columns denoting the
	// primary key for the roles relation (M2M).
	RolesPrimaryKey = []string{"user_id", "role_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// RealNameValidator is a validator for the "real_name" field. It is called by the builders before save.
	RealNameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
	StatusLocked   Status = "locked"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusLocked:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByRealName orders the results by the real_name field.
func ByRealName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealName, opts...).ToFunc()
}

// ByDepartment orders the results by the department field.
func ByDepartment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartment, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRolesCount orders the results by roles count.
func ByRolesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRolesStep(), opts...)
	}
}

// ByRoles orders the results by roles terms.
func ByRoles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRolesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreatedPurchaseOrdersCount orders the results by created_purchase_orders count.
func ByCreatedPurchaseOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedPurchaseOrdersStep(), opts...)
	}
}

// ByCreatedPurchaseOrders orders the results by created_purchase_orders terms.
func ByCreatedPurchaseOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedPurchaseOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInventoryRecordsCount orders the results by inventory_records count.
func ByInventoryRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoryRecordsStep(), opts...)
	}
}

// ByInventoryRecords orders the results by inventory_records terms.
func ByInventoryRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoryRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInitiatedApprovalsCount orders the results by initiated_approvals count.
func ByInitiatedApprovalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInitiatedApprovalsStep(), opts...)
	}
}

// ByInitiatedApprovals orders the results by initiated_approvals terms.
func ByInitiatedApprovals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInitiatedApprovalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRepairTicketsCount orders the results by repair_tickets count.
func ByRepairTicketsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRepairTicketsStep(), opts...)
	}
}

// ByRepairTickets orders the results by repair_tickets terms.
func ByRepairTickets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepairTicketsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRolesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RolesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, RolesTable, RolesPrimaryKey...),
	)
}
func newCreatedPurchaseOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedPurchaseOrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedPurchaseOrdersTable, CreatedPurchaseOrdersColumn),
	)
}
func newInventoryRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoryRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InventoryRecordsTable, InventoryRecordsColumn),
	)
}
func newInitiatedApprovalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InitiatedApprovalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InitiatedApprovalsTable, InitiatedApprovalsColumn),
	)
}
func newRepairTicketsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepairTicketsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RepairTicketsTable, RepairTicketsColumn),
	)
}
