// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Approval is the predicate function for approval builders.
type Approval func(*sql.Selector)

// ApprovalNode is the predicate function for approvalnode builders.
type ApprovalNode func(*sql.Selector)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// AssetType is the predicate function for assettype builders.
type AssetType func(*sql.Selector)

// DataCenter is the predicate function for datacenter builders.
type DataCenter func(*sql.Selector)

// IPAddress is the predicate function for ipaddress builders.
type IPAddress func(*sql.Selector)

// InventoryRecord is the predicate function for inventoryrecord builders.
type InventoryRecord func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// NetworkConnection is the predicate function for networkconnection builders.
type NetworkConnection func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// PurchaseOrder is the predicate function for purchaseorder builders.
type PurchaseOrder func(*sql.Selector)

// Rack is the predicate function for rack builders.
type Rack func(*sql.Selector)

// RackUnit is the predicate function for rackunit builders.
type RackUnit func(*sql.Selector)

// RepairTicket is the predicate function for repairticket builders.
type RepairTicket func(*sql.Selector)

// RepairVendor is the predicate function for repairvendor builders.
type RepairVendor func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// Supplier is the predicate function for supplier builders.
type Supplier func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Warehouse is the predicate function for warehouse builders.
type Warehouse func(*sql.Selector)
