// Code generated by ent, DO NOT EDIT.

package inventoryrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/your-org/atlas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldID, id))
}

// RecordNo applies equality check predicate on the "record_no" field. It's identical to RecordNoEQ.
func RecordNo(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldRecordNo, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldQuantity, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldReason, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldNote, v))
}

// FromLocationName applies equality check predicate on the "from_location_name" field. It's identical to FromLocationNameEQ.
func FromLocationName(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldFromLocationName, v))
}

// ToLocationName applies equality check predicate on the "to_location_name" field. It's identical to ToLocationNameEQ.
func ToLocationName(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldToLocationName, v))
}

// TransactionDate applies equality check predicate on the "transaction_date" field. It's identical to TransactionDateEQ.
func TransactionDate(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldTransactionDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// RecordNoEQ applies the EQ predicate on the "record_no" field.
func RecordNoEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldRecordNo, v))
}

// RecordNoNEQ applies the NEQ predicate on the "record_no" field.
func RecordNoNEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldRecordNo, v))
}

// RecordNoIn applies the In predicate on the "record_no" field.
func RecordNoIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldRecordNo, vs...))
}

// RecordNoNotIn applies the NotIn predicate on the "record_no" field.
func RecordNoNotIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldRecordNo, vs...))
}

// RecordNoGT applies the GT predicate on the "record_no" field.
func RecordNoGT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldRecordNo, v))
}

// RecordNoGTE applies the GTE predicate on the "record_no" field.
func RecordNoGTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldRecordNo, v))
}

// RecordNoLT applies the LT predicate on the "record_no" field.
func RecordNoLT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldRecordNo, v))
}

// RecordNoLTE applies the LTE predicate on the "record_no" field.
func RecordNoLTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldRecordNo, v))
}

// RecordNoContains applies the Contains predicate on the "record_no" field.
func RecordNoContains(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContains(FieldRecordNo, v))
}

// RecordNoHasPrefix applies the HasPrefix predicate on the "record_no" field.
func RecordNoHasPrefix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasPrefix(FieldRecordNo, v))
}

// RecordNoHasSuffix applies the HasSuffix predicate on the "record_no" field.
func RecordNoHasSuffix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasSuffix(FieldRecordNo, v))
}

// RecordNoEqualFold applies the EqualFold predicate on the "record_no" field.
func RecordNoEqualFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEqualFold(FieldRecordNo, v))
}

// RecordNoContainsFold applies the ContainsFold predicate on the "record_no" field.
func RecordNoContainsFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContainsFold(FieldRecordNo, v))
}

// RecordTypeEQ applies the EQ predicate on the "record_type" field.
func RecordTypeEQ(v RecordType) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldRecordType, v))
}

// RecordTypeNEQ applies the NEQ predicate on the "record_type" field.
func RecordTypeNEQ(v RecordType) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldRecordType, v))
}

// RecordTypeIn applies the In predicate on the "record_type" field.
func RecordTypeIn(vs ...RecordType) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldRecordType, vs...))
}

// RecordTypeNotIn applies the NotIn predicate on the "record_type" field.
func RecordTypeNotIn(vs ...RecordType) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldRecordType, vs...))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldQuantity, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContainsFold(FieldReason, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContainsFold(FieldNote, v))
}

// FromLocationNameEQ applies the EQ predicate on the "from_location_name" field.
func FromLocationNameEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldFromLocationName, v))
}

// FromLocationNameNEQ applies the NEQ predicate on the "from_location_name" field.
func FromLocationNameNEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldFromLocationName, v))
}

// FromLocationNameIn applies the In predicate on the "from_location_name" field.
func FromLocationNameIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldFromLocationName, vs...))
}

// FromLocationNameNotIn applies the NotIn predicate on the "from_location_name" field.
func FromLocationNameNotIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldFromLocationName, vs...))
}

// FromLocationNameGT applies the GT predicate on the "from_location_name" field.
func FromLocationNameGT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldFromLocationName, v))
}

// FromLocationNameGTE applies the GTE predicate on the "from_location_name" field.
func FromLocationNameGTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldFromLocationName, v))
}

// FromLocationNameLT applies the LT predicate on the "from_location_name" field.
func FromLocationNameLT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldFromLocationName, v))
}

// FromLocationNameLTE applies the LTE predicate on the "from_location_name" field.
func FromLocationNameLTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldFromLocationName, v))
}

// FromLocationNameContains applies the Contains predicate on the "from_location_name" field.
func FromLocationNameContains(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContains(FieldFromLocationName, v))
}

// FromLocationNameHasPrefix applies the HasPrefix predicate on the "from_location_name" field.
func FromLocationNameHasPrefix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasPrefix(FieldFromLocationName, v))
}

// FromLocationNameHasSuffix applies the HasSuffix predicate on the "from_location_name" field.
func FromLocationNameHasSuffix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasSuffix(FieldFromLocationName, v))
}

// FromLocationNameIsNil applies the IsNil predicate on the "from_location_name" field.
func FromLocationNameIsNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIsNull(FieldFromLocationName))
}

// FromLocationNameNotNil applies the NotNil predicate on the "from_location_name" field.
func FromLocationNameNotNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotNull(FieldFromLocationName))
}

// FromLocationNameEqualFold applies the EqualFold predicate on the "from_location_name" field.
func FromLocationNameEqualFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEqualFold(FieldFromLocationName, v))
}

// FromLocationNameContainsFold applies the ContainsFold predicate on the "from_location_name" field.
func FromLocationNameContainsFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContainsFold(FieldFromLocationName, v))
}

// ToLocationNameEQ applies the EQ predicate on the "to_location_name" field.
func ToLocationNameEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldToLocationName, v))
}

// ToLocationNameNEQ applies the NEQ predicate on the "to_location_name" field.
func ToLocationNameNEQ(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldToLocationName, v))
}

// ToLocationNameIn applies the In predicate on the "to_location_name" field.
func ToLocationNameIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldToLocationName, vs...))
}

// ToLocationNameNotIn applies the NotIn predicate on the "to_location_name" field.
func ToLocationNameNotIn(vs ...string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldToLocationName, vs...))
}

// ToLocationNameGT applies the GT predicate on the "to_location_name" field.
func ToLocationNameGT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldToLocationName, v))
}

// ToLocationNameGTE applies the GTE predicate on the "to_location_name" field.
func ToLocationNameGTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldToLocationName, v))
}

// ToLocationNameLT applies the LT predicate on the "to_location_name" field.
func ToLocationNameLT(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldToLocationName, v))
}

// ToLocationNameLTE applies the LTE predicate on the "to_location_name" field.
func ToLocationNameLTE(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldToLocationName, v))
}

// ToLocationNameContains applies the Contains predicate on the "to_location_name" field.
func ToLocationNameContains(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContains(FieldToLocationName, v))
}

// ToLocationNameHasPrefix applies the HasPrefix predicate on the "to_location_name" field.
func ToLocationNameHasPrefix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasPrefix(FieldToLocationName, v))
}

// ToLocationNameHasSuffix applies the HasSuffix predicate on the "to_location_name" field.
func ToLocationNameHasSuffix(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldHasSuffix(FieldToLocationName, v))
}

// ToLocationNameIsNil applies the IsNil predicate on the "to_location_name" field.
func ToLocationNameIsNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIsNull(FieldToLocationName))
}

// ToLocationNameNotNil applies the NotNil predicate on the "to_location_name" field.
func ToLocationNameNotNil() predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotNull(FieldToLocationName))
}

// ToLocationNameEqualFold applies the EqualFold predicate on the "to_location_name" field.
func ToLocationNameEqualFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEqualFold(FieldToLocationName, v))
}

// ToLocationNameContainsFold applies the ContainsFold predicate on the "to_location_name" field.
func ToLocationNameContainsFold(v string) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldContainsFold(FieldToLocationName, v))
}

// TransactionDateEQ applies the EQ predicate on the "transaction_date" field.
func TransactionDateEQ(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldTransactionDate, v))
}

// TransactionDateNEQ applies the NEQ predicate on the "transaction_date" field.
func TransactionDateNEQ(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldTransactionDate, v))
}

// TransactionDateIn applies the In predicate on the "transaction_date" field.
func TransactionDateIn(vs ...time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldTransactionDate, vs...))
}

// TransactionDateNotIn applies the NotIn predicate on the "transaction_date" field.
func TransactionDateNotIn(vs ...time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldTransactionDate, vs...))
}

// TransactionDateGT applies the GT predicate on the "transaction_date" field.
func TransactionDateGT(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldTransactionDate, v))
}

// TransactionDateGTE applies the GTE predicate on the "transaction_date" field.
func TransactionDateGTE(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldTransactionDate, v))
}

// TransactionDateLT applies the LT predicate on the "transaction_date" field.
func TransactionDateLT(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldTransactionDate, v))
}

// TransactionDateLTE applies the LTE predicate on the "transaction_date" field.
func TransactionDateLTE(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldTransactionDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAsset applies the HasEdge predicate on the "asset" edge.
func HasAsset() predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.Asset) predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := newAssetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFromLocation applies the HasEdge predicate on the "from_location" edge.
func HasFromLocation() predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FromLocationTable, FromLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromLocationWith applies the HasEdge predicate on the "from_location" edge with a given conditions (other predicates).
func HasFromLocationWith(preds ...predicate.Location) predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := newFromLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToLocation applies the HasEdge predicate on the "to_location" edge.
func HasToLocation() predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ToLocationTable, ToLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasToLocationWith applies the HasEdge predicate on the "to_location" edge with a given conditions (other predicates).
func HasToLocationWith(preds ...predicate.Location) predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := newToLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOperator applies the HasEdge predicate on the "operator" edge.
func HasOperator() predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OperatorTable, OperatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperatorWith applies the HasEdge predicate on the "operator" edge with a given conditions (other predicates).
func HasOperatorWith(preds ...predicate.User) predicate.InventoryRecord {
	return predicate.InventoryRecord(func(s *sql.Selector) {
		step := newOperatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InventoryRecord) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InventoryRecord) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InventoryRecord) predicate.InventoryRecord {
	return predicate.InventoryRecord(sql.NotPredicates(p))
}
