// Code generated by ent, DO NOT EDIT.

package rackunit

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rackunit type in the database.
	Label = "rack_unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUnitNumber holds the string denoting the unit_number field in the database.
	FieldUnitNumber = "unit_number"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRack holds the string denoting the rack edge name in mutations.
	EdgeRack = "rack"
	// EdgeAsset holds the string denoting the asset edge name in mutations.
	EdgeAsset = "asset"
	// Table holds the table name of the rackunit in the database.
	Table = "rack_units"
	// RackTable is the table that holds the rack relation/edge.
	RackTable = "rack_units"
	// RackInverseTable is the table name for the Rack entity.
	// It exists in this package in order to avoid circular dependency with the "rack" package.
	RackInverseTable = "racks"
	// RackColumn is the table column denoting the rack relation/edge.
	RackColumn = "rack_units"
	// AssetTable is the table that holds the asset relation/edge.
	AssetTable = "assets"
	// AssetInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	AssetInverseTable = "assets"
	// AssetColumn is the table column denoting the asset relation/edge.
	AssetColumn = "rack_unit_asset"
)

// Columns holds all SQL columns for rackunit fields.
var Columns = []string{
	FieldID,
	FieldUnitNumber,
	FieldHeight,
	FieldStatus,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "rack_units"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"rack_units",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHeight holds the default value on creation for the "height" field.
	DefaultHeight int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusAvailable is the default value of the Status enum.
const DefaultStatus = StatusAvailable

// Status values.
const (
	StatusAvailable Status = "available"
	StatusOccupied  Status = "occupied"
	StatusReserved  Status = "reserved"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusOccupied, StatusReserved:
		return nil
	default:
		return fmt.Errorf("rackunit: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the RackUnit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUnitNumber orders the results by the unit_number field.
func ByUnitNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitNumber, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRackField orders the results by rack field.
func ByRackField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRackStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssetField orders the results by asset field.
func ByAssetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetStep(), sql.OrderByField(field, opts...))
	}
}
func newRackStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RackInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RackTable, RackColumn),
	)
}
func newAssetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, AssetTable, AssetColumn),
	)
}
