// Code generated by ent, DO NOT EDIT.

package location

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the location type in the database.
	Label = "location"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldLocationCode holds the string denoting the location_code field in the database.
	FieldLocationCode = "location_code"
	// FieldParentLocationID holds the string denoting the parent_location_id field in the database.
	FieldParentLocationID = "parent_location_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeWarehouse holds the string denoting the warehouse edge name in mutations.
	EdgeWarehouse = "warehouse"
	// EdgeAssets holds the string denoting the assets edge name in mutations.
	EdgeAssets = "assets"
	// EdgeInventoryRecordsFrom holds the string denoting the inventory_records_from edge name in mutations.
	EdgeInventoryRecordsFrom = "inventory_records_from"
	// EdgeInventoryRecordsTo holds the string denoting the inventory_records_to edge name in mutations.
	EdgeInventoryRecordsTo = "inventory_records_to"
	// Table holds the table name of the location in the database.
	Table = "locations"
	// WarehouseTable is the table that holds the warehouse relation/edge.
	WarehouseTable = "locations"
	// WarehouseInverseTable is the table name for the Warehouse entity.
	// It exists in this package in order to avoid circular dependency with the "warehouse" package.
	WarehouseInverseTable = "warehouses"
	// WarehouseColumn is the table column denoting the warehouse relation/edge.
	WarehouseColumn = "warehouse_locations"
	// AssetsTable is the table that holds the assets relation/edge.
	AssetsTable = "assets"
	// AssetsInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	AssetsInverseTable = "assets"
	// AssetsColumn is the table column denoting the assets relation/edge.
	AssetsColumn = "location_assets"
	// InventoryRecordsFromTable is the table that holds the inventory_records_from relation/edge.
	InventoryRecordsFromTable = "inventory_records"
	// InventoryRecordsFromInverseTable is the table name for the InventoryRecord entity.
	// It exists in this package in order to avoid circular dependency with the "inventoryrecord" package.
	InventoryRecordsFromInverseTable = "inventory_records"
	// InventoryRecordsFromColumn is the table column denoting the inventory_records_from relation/edge.
	InventoryRecordsFromColumn = "location_inventory_records_from"
	// InventoryRecordsToTable is the table that holds the inventory_records_to relation/edge.
	InventoryRecordsToTable = "inventory_records"
	// InventoryRecordsToInverseTable is the table name for the InventoryRecord entity.
	// It exists in this package in order to avoid circular dependency with the "inventoryrecord" package.
	InventoryRecordsToInverseTable = "inventory_records"
	// InventoryRecordsToColumn is the table column denoting the inventory_records_to relation/edge.
	InventoryRecordsToColumn = "location_inventory_records_to"
)

// Columns holds all SQL columns for location fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCode,
	FieldLocationCode,
	FieldParentLocationID,
	FieldStatus,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "locations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"warehouse_locations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusAvailable is the default value of the Status enum.
const DefaultStatus = StatusAvailable

// Status values.
const (
	StatusAvailable   Status = "available"
	StatusFull        Status = "full"
	StatusMaintenance Status = "maintenance"
	StatusReserved    Status = "reserved"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusFull, StatusMaintenance, StatusReserved:
		return nil
	default:
		return fmt.Errorf("location: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Location queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByLocationCode orders the results by the location_code field.
func ByLocationCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocationCode, opts...).ToFunc()
}

// ByParentLocationID orders the results by the parent_location_id field.
func ByParentLocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentLocationID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWarehouseField orders the results by warehouse field.
func ByWarehouseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWarehouseStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssetsCount orders the results by assets count.
func ByAssetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssetsStep(), opts...)
	}
}

// ByAssets orders the results by assets terms.
func ByAssets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInventoryRecordsFromCount orders the results by inventory_records_from count.
func ByInventoryRecordsFromCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoryRecordsFromStep(), opts...)
	}
}

// ByInventoryRecordsFrom orders the results by inventory_records_from terms.
func ByInventoryRecordsFrom(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoryRecordsFromStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInventoryRecordsToCount orders the results by inventory_records_to count.
func ByInventoryRecordsToCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoryRecordsToStep(), opts...)
	}
}

// ByInventoryRecordsTo orders the results by inventory_records_to terms.
func ByInventoryRecordsTo(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoryRecordsToStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newWarehouseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WarehouseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WarehouseTable, WarehouseColumn),
	)
}
func newAssetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssetsTable, AssetsColumn),
	)
}
func newInventoryRecordsFromStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoryRecordsFromInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InventoryRecordsFromTable, InventoryRecordsFromColumn),
	)
}
func newInventoryRecordsToStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoryRecordsToInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InventoryRecordsToTable, InventoryRecordsToColumn),
	)
}
