// Code generated by ent, DO NOT EDIT.

package asset

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the asset type in the database.
	Label = "asset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAssetNo holds the string denoting the asset_no field in the database.
	FieldAssetNo = "asset_no"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBrand holds the string denoting the brand field in the database.
	FieldBrand = "brand"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldSn holds the string denoting the sn field in the database.
	FieldSn = "sn"
	// FieldProjectZone holds the string denoting the project_zone field in the database.
	FieldProjectZone = "project_zone"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBorrowStatus holds the string denoting the borrow_status field in the database.
	FieldBorrowStatus = "borrow_status"
	// FieldBorrowedByID holds the string denoting the borrowed_by_id field in the database.
	FieldBorrowedByID = "borrowed_by_id"
	// FieldBorrowedAt holds the string denoting the borrowed_at field in the database.
	FieldBorrowedAt = "borrowed_at"
	// FieldExpectedReturnAt holds the string denoting the expected_return_at field in the database.
	FieldExpectedReturnAt = "expected_return_at"
	// FieldSpecs holds the string denoting the specs field in the database.
	FieldSpecs = "specs"
	// FieldPurchaseDate holds the string denoting the purchase_date field in the database.
	FieldPurchaseDate = "purchase_date"
	// FieldWarrantyExpireDate holds the string denoting the warranty_expire_date field in the database.
	FieldWarrantyExpireDate = "warranty_expire_date"
	// FieldPurchasePrice holds the string denoting the purchase_price field in the database.
	FieldPurchasePrice = "purchase_price"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAssetType holds the string denoting the asset_type edge name in mutations.
	EdgeAssetType = "asset_type"
	// EdgeLocation holds the string denoting the location edge name in mutations.
	EdgeLocation = "location"
	// EdgeRackUnit holds the string denoting the rack_unit edge name in mutations.
	EdgeRackUnit = "rack_unit"
	// EdgeInventoryRecords holds the string denoting the inventory_records edge name in mutations.
	EdgeInventoryRecords = "inventory_records"
	// EdgeRepairTickets holds the string denoting the repair_tickets edge name in mutations.
	EdgeRepairTickets = "repair_tickets"
	// EdgeNetworkConnectionsSource holds the string denoting the network_connections_source edge name in mutations.
	EdgeNetworkConnectionsSource = "network_connections_source"
	// EdgeNetworkConnectionsTarget holds the string denoting the network_connections_target edge name in mutations.
	EdgeNetworkConnectionsTarget = "network_connections_target"
	// EdgeIPAddresses holds the string denoting the ip_addresses edge name in mutations.
	EdgeIPAddresses = "ip_addresses"
	// Table holds the table name of the asset in the database.
	Table = "assets"
	// AssetTypeTable is the table that holds the asset_type relation/edge.
	AssetTypeTable = "assets"
	// AssetTypeInverseTable is the table name for the AssetType entity.
	// It exists in this package in order to avoid circular dependency with the "assettype" package.
	AssetTypeInverseTable = "asset_types"
	// AssetTypeColumn is the table column denoting the asset_type relation/edge.
	AssetTypeColumn = "asset_type_assets"
	// LocationTable is the table that holds the location relation/edge.
	LocationTable = "assets"
	// LocationInverseTable is the table name for the Location entity.
	// It exists in this package in order to avoid circular dependency with the "location" package.
	LocationInverseTable = "locations"
	// LocationColumn is the table column denoting the location relation/edge.
	LocationColumn = "location_assets"
	// RackUnitTable is the table that holds the rack_unit relation/edge.
	RackUnitTable = "assets"
	// RackUnitInverseTable is the table name for the RackUnit entity.
	// It exists in this package in order to avoid circular dependency with the "rackunit" package.
	RackUnitInverseTable = "rack_units"
	// RackUnitColumn is the table column denoting the rack_unit relation/edge.
	RackUnitColumn = "rack_unit_asset"
	// InventoryRecordsTable is the table that holds the inventory_records relation/edge.
	InventoryRecordsTable = "inventory_records"
	// InventoryRecordsInverseTable is the table name for the InventoryRecord entity.
	// It exists in this package in order to avoid circular dependency with the "inventoryrecord" package.
	InventoryRecordsInverseTable = "inventory_records"
	// InventoryRecordsColumn is the table column denoting the inventory_records relation/edge.
	InventoryRecordsColumn = "asset_inventory_records"
	// RepairTicketsTable is the table that holds the repair_tickets relation/edge.
	RepairTicketsTable = "repair_tickets"
	// RepairTicketsInverseTable is the table name for the RepairTicket entity.
	// It exists in this package in order to avoid circular dependency with the "repairticket" package.
	RepairTicketsInverseTable = "repair_tickets"
	// RepairTicketsColumn is the table column denoting the repair_tickets relation/edge.
	RepairTicketsColumn = "asset_repair_tickets"
	// NetworkConnectionsSourceTable is the table that holds the network_connections_source relation/edge.
	NetworkConnectionsSourceTable = "network_connections"
	// NetworkConnectionsSourceInverseTable is the table name for the NetworkConnection entity.
	// It exists in this package in order to avoid circular dependency with the "networkconnection" package.
	NetworkConnectionsSourceInverseTable = "network_connections"
	// NetworkConnectionsSourceColumn is the table column denoting the network_connections_source relation/edge.
	NetworkConnectionsSourceColumn = "asset_network_connections_source"
	// NetworkConnectionsTargetTable is the table that holds the network_connections_target relation/edge.
	NetworkConnectionsTargetTable = "network_connections"
	// NetworkConnectionsTargetInverseTable is the table name for the NetworkConnection entity.
	// It exists in this package in order to avoid circular dependency with the "networkconnection" package.
	NetworkConnectionsTargetInverseTable = "network_connections"
	// NetworkConnectionsTargetColumn is the table column denoting the network_connections_target relation/edge.
	NetworkConnectionsTargetColumn = "asset_network_connections_target"
	// IPAddressesTable is the table that holds the ip_addresses relation/edge.
	IPAddressesTable = "ip_addresses"
	// IPAddressesInverseTable is the table name for the IPAddress entity.
	// It exists in this package in order to avoid circular dependency with the "ipaddress" package.
	IPAddressesInverseTable = "ip_addresses"
	// IPAddressesColumn is the table column denoting the ip_addresses relation/edge.
	IPAddressesColumn = "asset_ip_addresses"
)

// Columns holds all SQL columns for asset fields.
var Columns = []string{
	FieldID,
	FieldAssetNo,
	FieldName,
	FieldBrand,
	FieldModel,
	FieldSn,
	FieldProjectZone,
	FieldStatus,
	FieldBorrowStatus,
	FieldBorrowedByID,
	FieldBorrowedAt,
	FieldExpectedReturnAt,
	FieldSpecs,
	FieldPurchaseDate,
	FieldWarrantyExpireDate,
	FieldPurchasePrice,
	FieldDescription,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "assets"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"asset_type_assets",
	"location_assets",
	"rack_unit_asset",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// AssetNoValidator is a validator for the "asset_no" field. It is called by the builders before save.
	AssetNoValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// ProjectZone defines the type for the "project_zone" enum field.
type ProjectZone string

// ProjectZone values.
const (
	ProjectZoneAiCloud       ProjectZone = "ai_cloud"
	ProjectZoneHpcCloud      ProjectZone = "hpc_cloud"
	ProjectZoneIndustryCloud ProjectZone = "industry_cloud"
	ProjectZoneOther         ProjectZone = "other"
)

func (pz ProjectZone) String() string {
	return string(pz)
}

// ProjectZoneValidator is a validator for the "project_zone" field enum values. It is called by the builders before save.
func ProjectZoneValidator(pz ProjectZone) error {
	switch pz {
	case ProjectZoneAiCloud, ProjectZoneHpcCloud, ProjectZoneIndustryCloud, ProjectZoneOther:
		return nil
	default:
		return fmt.Errorf("asset: invalid enum value for project_zone field: %q", pz)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusInStock is the default value of the Status enum.
const DefaultStatus = StatusInStock

// Status values.
const (
	StatusInStock     Status = "in_stock"
	StatusDeployed    Status = "deployed"
	StatusBorrowed    Status = "borrowed"
	StatusInTransit   Status = "in_transit"
	StatusMaintenance Status = "maintenance"
	StatusRetired     Status = "retired"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusInStock, StatusDeployed, StatusBorrowed, StatusInTransit, StatusMaintenance, StatusRetired:
		return nil
	default:
		return fmt.Errorf("asset: invalid enum value for status field: %q", s)
	}
}

// BorrowStatus defines the type for the "borrow_status" enum field.
type BorrowStatus string

// BorrowStatusAvailable is the default value of the BorrowStatus enum.
const DefaultBorrowStatus = BorrowStatusAvailable

// BorrowStatus values.
const (
	BorrowStatusAvailable BorrowStatus = "available"
	BorrowStatusBorrowed  BorrowStatus = "borrowed"
	BorrowStatusReserved  BorrowStatus = "reserved"
)

func (bs BorrowStatus) String() string {
	return string(bs)
}

// BorrowStatusValidator is a validator for the "borrow_status" field enum values. It is called by the builders before save.
func BorrowStatusValidator(bs BorrowStatus) error {
	switch bs {
	case BorrowStatusAvailable, BorrowStatusBorrowed, BorrowStatusReserved:
		return nil
	default:
		return fmt.Errorf("asset: invalid enum value for borrow_status field: %q", bs)
	}
}

// OrderOption defines the ordering options for the Asset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAssetNo orders the results by the asset_no field.
func ByAssetNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetNo, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBrand orders the results by the brand field.
func ByBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrand, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// BySn orders the results by the sn field.
func BySn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSn, opts...).ToFunc()
}

// ByProjectZone orders the results by the project_zone field.
func ByProjectZone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectZone, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBorrowStatus orders the results by the borrow_status field.
func ByBorrowStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBorrowStatus, opts...).ToFunc()
}

// ByBorrowedByID orders the results by the borrowed_by_id field.
func ByBorrowedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBorrowedByID, opts...).ToFunc()
}

// ByBorrowedAt orders the results by the borrowed_at field.
func ByBorrowedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBorrowedAt, opts...).ToFunc()
}

// ByExpectedReturnAt orders the results by the expected_return_at field.
func ByExpectedReturnAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedReturnAt, opts...).ToFunc()
}

// ByPurchaseDate orders the results by the purchase_date field.
func ByPurchaseDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseDate, opts...).ToFunc()
}

// ByWarrantyExpireDate orders the results by the warranty_expire_date field.
func ByWarrantyExpireDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarrantyExpireDate, opts...).ToFunc()
}

// ByPurchasePrice orders the results by the purchase_price field.
func ByPurchasePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchasePrice, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAssetTypeField orders the results by asset_type field.
func ByAssetTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetTypeStep(), sql.OrderByField(field, opts...))
	}
}

// ByLocationField orders the results by location field.
func ByLocationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLocationStep(), sql.OrderByField(field, opts...))
	}
}

// ByRackUnitField orders the results by rack_unit field.
func ByRackUnitField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRackUnitStep(), sql.OrderByField(field, opts...))
	}
}

// ByInventoryRecordsCount orders the results by inventory_records count.
func ByInventoryRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoryRecordsStep(), opts...)
	}
}

// ByInventoryRecords orders the results by inventory_records terms.
func ByInventoryRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoryRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRepairTicketsCount orders the results by repair_tickets count.
func ByRepairTicketsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRepairTicketsStep(), opts...)
	}
}

// ByRepairTickets orders the results by repair_tickets terms.
func ByRepairTickets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepairTicketsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNetworkConnectionsSourceCount orders the results by network_connections_source count.
func ByNetworkConnectionsSourceCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNetworkConnectionsSourceStep(), opts...)
	}
}

// ByNetworkConnectionsSource orders the results by network_connections_source terms.
func ByNetworkConnectionsSource(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNetworkConnectionsSourceStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNetworkConnectionsTargetCount orders the results by network_connections_target count.
func ByNetworkConnectionsTargetCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNetworkConnectionsTargetStep(), opts...)
	}
}

// ByNetworkConnectionsTarget orders the results by network_connections_target terms.
func ByNetworkConnectionsTarget(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNetworkConnectionsTargetStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIPAddressesCount orders the results by ip_addresses count.
func ByIPAddressesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIPAddressesStep(), opts...)
	}
}

// ByIPAddresses orders the results by ip_addresses terms.
func ByIPAddresses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIPAddressesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAssetTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssetTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssetTypeTable, AssetTypeColumn),
	)
}
func newLocationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LocationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
	)
}
func newRackUnitStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RackUnitInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, RackUnitTable, RackUnitColumn),
	)
}
func newInventoryRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoryRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InventoryRecordsTable, InventoryRecordsColumn),
	)
}
func newRepairTicketsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepairTicketsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RepairTicketsTable, RepairTicketsColumn),
	)
}
func newNetworkConnectionsSourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NetworkConnectionsSourceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NetworkConnectionsSourceTable, NetworkConnectionsSourceColumn),
	)
}
func newNetworkConnectionsTargetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NetworkConnectionsTargetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NetworkConnectionsTargetTable, NetworkConnectionsTargetColumn),
	)
}
func newIPAddressesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IPAddressesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IPAddressesTable, IPAddressesColumn),
	)
}
