// Code generated by ent, DO NOT EDIT.

package supplier

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supplier type in the database.
	Label = "supplier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldCategorySpecialties holds the string denoting the category_specialties field in the database.
	FieldCategorySpecialties = "category_specialties"
	// FieldContactPerson holds the string denoting the contact_person field in the database.
	FieldContactPerson = "contact_person"
	// FieldContactPhone holds the string denoting the contact_phone field in the database.
	FieldContactPhone = "contact_phone"
	// FieldContactEmail holds the string denoting the contact_email field in the database.
	FieldContactEmail = "contact_email"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePurchaseOrders holds the string denoting the purchase_orders edge name in mutations.
	EdgePurchaseOrders = "purchase_orders"
	// EdgeRepairVendors holds the string denoting the repair_vendors edge name in mutations.
	EdgeRepairVendors = "repair_vendors"
	// Table holds the table name of the supplier in the database.
	Table = "suppliers"
	// PurchaseOrdersTable is the table that holds the purchase_orders relation/edge.
	PurchaseOrdersTable = "purchase_orders"
	// PurchaseOrdersInverseTable is the table name for the PurchaseOrder entity.
	// It exists in this package in order to avoid circular dependency with the "purchaseorder" package.
	PurchaseOrdersInverseTable = "purchase_orders"
	// PurchaseOrdersColumn is the table column denoting the purchase_orders relation/edge.
	PurchaseOrdersColumn = "supplier_purchase_orders"
	// RepairVendorsTable is the table that holds the repair_vendors relation/edge.
	RepairVendorsTable = "repair_vendors"
	// RepairVendorsInverseTable is the table name for the RepairVendor entity.
	// It exists in this package in order to avoid circular dependency with the "repairvendor" package.
	RepairVendorsInverseTable = "repair_vendors"
	// RepairVendorsColumn is the table column denoting the repair_vendors relation/edge.
	RepairVendorsColumn = "supplier_repair_vendors"
)

// Columns holds all SQL columns for supplier fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCode,
	FieldCategorySpecialties,
	FieldContactPerson,
	FieldContactPhone,
	FieldContactEmail,
	FieldAddress,
	FieldRating,
	FieldStatus,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultRating holds the default value on creation for the "rating" field.
	DefaultRating float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusInactive  Status = "inactive"
	StatusBlacklist Status = "blacklist"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusBlacklist:
		return nil
	default:
		return fmt.Errorf("supplier: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Supplier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByContactPerson orders the results by the contact_person field.
func ByContactPerson(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPerson, opts...).ToFunc()
}

// ByContactPhone orders the results by the contact_phone field.
func ByContactPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPhone, opts...).ToFunc()
}

// ByContactEmail orders the results by the contact_email field.
func ByContactEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactEmail, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPurchaseOrdersCount orders the results by purchase_orders count.
func ByPurchaseOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPurchaseOrdersStep(), opts...)
	}
}

// ByPurchaseOrders orders the results by purchase_orders terms.
func ByPurchaseOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPurchaseOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRepairVendorsCount orders the results by repair_vendors count.
func ByRepairVendorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRepairVendorsStep(), opts...)
	}
}

// ByRepairVendors orders the results by repair_vendors terms.
func ByRepairVendors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepairVendorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPurchaseOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PurchaseOrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PurchaseOrdersTable, PurchaseOrdersColumn),
	)
}
func newRepairVendorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepairVendorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RepairVendorsTable, RepairVendorsColumn),
	)
}
