// Code generated by ent, DO NOT EDIT.

package orderitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the orderitem type in the database.
	Label = "order_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldModelConfig holds the string denoting the model_config field in the database.
	FieldModelConfig = "model_config"
	// FieldWarrantyPeriod holds the string denoting the warranty_period field in the database.
	FieldWarrantyPeriod = "warranty_period"
	// FieldDeliveryTimeline holds the string denoting the delivery_timeline field in the database.
	FieldDeliveryTimeline = "delivery_timeline"
	// FieldRequiredQty holds the string denoting the required_qty field in the database.
	FieldRequiredQty = "required_qty"
	// FieldSpareQty holds the string denoting the spare_qty field in the database.
	FieldSpareQty = "spare_qty"
	// FieldAvailableStock holds the string denoting the available_stock field in the database.
	FieldAvailableStock = "available_stock"
	// FieldPurchaseQty holds the string denoting the purchase_qty field in the database.
	FieldPurchaseQty = "purchase_qty"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldTotalPrice holds the string denoting the total_price field in the database.
	FieldTotalPrice = "total_price"
	// FieldPurpose holds the string denoting the purpose field in the database.
	FieldPurpose = "purpose"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePurchaseOrder holds the string denoting the purchase_order edge name in mutations.
	EdgePurchaseOrder = "purchase_order"
	// Table holds the table name of the orderitem in the database.
	Table = "order_items"
	// PurchaseOrderTable is the table that holds the purchase_order relation/edge.
	PurchaseOrderTable = "order_items"
	// PurchaseOrderInverseTable is the table name for the PurchaseOrder entity.
	// It exists in this package in order to avoid circular dependency with the "purchaseorder" package.
	PurchaseOrderInverseTable = "purchase_orders"
	// PurchaseOrderColumn is the table column denoting the purchase_order relation/edge.
	PurchaseOrderColumn = "purchase_order_items"
)

// Columns holds all SQL columns for orderitem fields.
var Columns = []string{
	FieldID,
	FieldCategory,
	FieldModelConfig,
	FieldWarrantyPeriod,
	FieldDeliveryTimeline,
	FieldRequiredQty,
	FieldSpareQty,
	FieldAvailableStock,
	FieldPurchaseQty,
	FieldUnitPrice,
	FieldTotalPrice,
	FieldPurpose,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "order_items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"purchase_order_items",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultRequiredQty holds the default value on creation for the "required_qty" field.
	DefaultRequiredQty int
	// DefaultSpareQty holds the default value on creation for the "spare_qty" field.
	DefaultSpareQty int
	// DefaultAvailableStock holds the default value on creation for the "available_stock" field.
	DefaultAvailableStock int
	// DefaultPurchaseQty holds the default value on creation for the "purchase_qty" field.
	DefaultPurchaseQty int
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice float64
	// DefaultTotalPrice holds the default value on creation for the "total_price" field.
	DefaultTotalPrice float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OrderItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByModelConfig orders the results by the model_config field.
func ByModelConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelConfig, opts...).ToFunc()
}

// ByWarrantyPeriod orders the results by the warranty_period field.
func ByWarrantyPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarrantyPeriod, opts...).ToFunc()
}

// ByDeliveryTimeline orders the results by the delivery_timeline field.
func ByDeliveryTimeline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryTimeline, opts...).ToFunc()
}

// ByRequiredQty orders the results by the required_qty field.
func ByRequiredQty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiredQty, opts...).ToFunc()
}

// BySpareQty orders the results by the spare_qty field.
func BySpareQty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpareQty, opts...).ToFunc()
}

// ByAvailableStock orders the results by the available_stock field.
func ByAvailableStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableStock, opts...).ToFunc()
}

// ByPurchaseQty orders the results by the purchase_qty field.
func ByPurchaseQty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseQty, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByTotalPrice orders the results by the total_price field.
func ByTotalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrice, opts...).ToFunc()
}

// ByPurpose orders the results by the purpose field.
func ByPurpose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurpose, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPurchaseOrderField orders the results by purchase_order field.
func ByPurchaseOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPurchaseOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newPurchaseOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PurchaseOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PurchaseOrderTable, PurchaseOrderColumn),
	)
}
