// Code generated by ent, DO NOT EDIT.

package orderitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/your-org/atlas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldID, id))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldCategory, v))
}

// ModelConfig applies equality check predicate on the "model_config" field. It's identical to ModelConfigEQ.
func ModelConfig(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldModelConfig, v))
}

// WarrantyPeriod applies equality check predicate on the "warranty_period" field. It's identical to WarrantyPeriodEQ.
func WarrantyPeriod(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldWarrantyPeriod, v))
}

// DeliveryTimeline applies equality check predicate on the "delivery_timeline" field. It's identical to DeliveryTimelineEQ.
func DeliveryTimeline(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldDeliveryTimeline, v))
}

// RequiredQty applies equality check predicate on the "required_qty" field. It's identical to RequiredQtyEQ.
func RequiredQty(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldRequiredQty, v))
}

// SpareQty applies equality check predicate on the "spare_qty" field. It's identical to SpareQtyEQ.
func SpareQty(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldSpareQty, v))
}

// AvailableStock applies equality check predicate on the "available_stock" field. It's identical to AvailableStockEQ.
func AvailableStock(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldAvailableStock, v))
}

// PurchaseQty applies equality check predicate on the "purchase_qty" field. It's identical to PurchaseQtyEQ.
func PurchaseQty(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldPurchaseQty, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldUnitPrice, v))
}

// TotalPrice applies equality check predicate on the "total_price" field. It's identical to TotalPriceEQ.
func TotalPrice(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldTotalPrice, v))
}

// Purpose applies equality check predicate on the "purpose" field. It's identical to PurposeEQ.
func Purpose(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldPurpose, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContainsFold(FieldCategory, v))
}

// ModelConfigEQ applies the EQ predicate on the "model_config" field.
func ModelConfigEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldModelConfig, v))
}

// ModelConfigNEQ applies the NEQ predicate on the "model_config" field.
func ModelConfigNEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldModelConfig, v))
}

// ModelConfigIn applies the In predicate on the "model_config" field.
func ModelConfigIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldModelConfig, vs...))
}

// ModelConfigNotIn applies the NotIn predicate on the "model_config" field.
func ModelConfigNotIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldModelConfig, vs...))
}

// ModelConfigGT applies the GT predicate on the "model_config" field.
func ModelConfigGT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldModelConfig, v))
}

// ModelConfigGTE applies the GTE predicate on the "model_config" field.
func ModelConfigGTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldModelConfig, v))
}

// ModelConfigLT applies the LT predicate on the "model_config" field.
func ModelConfigLT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldModelConfig, v))
}

// ModelConfigLTE applies the LTE predicate on the "model_config" field.
func ModelConfigLTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldModelConfig, v))
}

// ModelConfigContains applies the Contains predicate on the "model_config" field.
func ModelConfigContains(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContains(FieldModelConfig, v))
}

// ModelConfigHasPrefix applies the HasPrefix predicate on the "model_config" field.
func ModelConfigHasPrefix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasPrefix(FieldModelConfig, v))
}

// ModelConfigHasSuffix applies the HasSuffix predicate on the "model_config" field.
func ModelConfigHasSuffix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasSuffix(FieldModelConfig, v))
}

// ModelConfigEqualFold applies the EqualFold predicate on the "model_config" field.
func ModelConfigEqualFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEqualFold(FieldModelConfig, v))
}

// ModelConfigContainsFold applies the ContainsFold predicate on the "model_config" field.
func ModelConfigContainsFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContainsFold(FieldModelConfig, v))
}

// WarrantyPeriodEQ applies the EQ predicate on the "warranty_period" field.
func WarrantyPeriodEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldWarrantyPeriod, v))
}

// WarrantyPeriodNEQ applies the NEQ predicate on the "warranty_period" field.
func WarrantyPeriodNEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldWarrantyPeriod, v))
}

// WarrantyPeriodIn applies the In predicate on the "warranty_period" field.
func WarrantyPeriodIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldWarrantyPeriod, vs...))
}

// WarrantyPeriodNotIn applies the NotIn predicate on the "warranty_period" field.
func WarrantyPeriodNotIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldWarrantyPeriod, vs...))
}

// WarrantyPeriodGT applies the GT predicate on the "warranty_period" field.
func WarrantyPeriodGT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldWarrantyPeriod, v))
}

// WarrantyPeriodGTE applies the GTE predicate on the "warranty_period" field.
func WarrantyPeriodGTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldWarrantyPeriod, v))
}

// WarrantyPeriodLT applies the LT predicate on the "warranty_period" field.
func WarrantyPeriodLT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldWarrantyPeriod, v))
}

// WarrantyPeriodLTE applies the LTE predicate on the "warranty_period" field.
func WarrantyPeriodLTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldWarrantyPeriod, v))
}

// WarrantyPeriodContains applies the Contains predicate on the "warranty_period" field.
func WarrantyPeriodContains(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContains(FieldWarrantyPeriod, v))
}

// WarrantyPeriodHasPrefix applies the HasPrefix predicate on the "warranty_period" field.
func WarrantyPeriodHasPrefix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasPrefix(FieldWarrantyPeriod, v))
}

// WarrantyPeriodHasSuffix applies the HasSuffix predicate on the "warranty_period" field.
func WarrantyPeriodHasSuffix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasSuffix(FieldWarrantyPeriod, v))
}

// WarrantyPeriodIsNil applies the IsNil predicate on the "warranty_period" field.
func WarrantyPeriodIsNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIsNull(FieldWarrantyPeriod))
}

// WarrantyPeriodNotNil applies the NotNil predicate on the "warranty_period" field.
func WarrantyPeriodNotNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotNull(FieldWarrantyPeriod))
}

// WarrantyPeriodEqualFold applies the EqualFold predicate on the "warranty_period" field.
func WarrantyPeriodEqualFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEqualFold(FieldWarrantyPeriod, v))
}

// WarrantyPeriodContainsFold applies the ContainsFold predicate on the "warranty_period" field.
func WarrantyPeriodContainsFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContainsFold(FieldWarrantyPeriod, v))
}

// DeliveryTimelineEQ applies the EQ predicate on the "delivery_timeline" field.
func DeliveryTimelineEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldDeliveryTimeline, v))
}

// DeliveryTimelineNEQ applies the NEQ predicate on the "delivery_timeline" field.
func DeliveryTimelineNEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldDeliveryTimeline, v))
}

// DeliveryTimelineIn applies the In predicate on the "delivery_timeline" field.
func DeliveryTimelineIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldDeliveryTimeline, vs...))
}

// DeliveryTimelineNotIn applies the NotIn predicate on the "delivery_timeline" field.
func DeliveryTimelineNotIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldDeliveryTimeline, vs...))
}

// DeliveryTimelineGT applies the GT predicate on the "delivery_timeline" field.
func DeliveryTimelineGT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldDeliveryTimeline, v))
}

// DeliveryTimelineGTE applies the GTE predicate on the "delivery_timeline" field.
func DeliveryTimelineGTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldDeliveryTimeline, v))
}

// DeliveryTimelineLT applies the LT predicate on the "delivery_timeline" field.
func DeliveryTimelineLT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldDeliveryTimeline, v))
}

// DeliveryTimelineLTE applies the LTE predicate on the "delivery_timeline" field.
func DeliveryTimelineLTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldDeliveryTimeline, v))
}

// DeliveryTimelineContains applies the Contains predicate on the "delivery_timeline" field.
func DeliveryTimelineContains(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContains(FieldDeliveryTimeline, v))
}

// DeliveryTimelineHasPrefix applies the HasPrefix predicate on the "delivery_timeline" field.
func DeliveryTimelineHasPrefix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasPrefix(FieldDeliveryTimeline, v))
}

// DeliveryTimelineHasSuffix applies the HasSuffix predicate on the "delivery_timeline" field.
func DeliveryTimelineHasSuffix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasSuffix(FieldDeliveryTimeline, v))
}

// DeliveryTimelineIsNil applies the IsNil predicate on the "delivery_timeline" field.
func DeliveryTimelineIsNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIsNull(FieldDeliveryTimeline))
}

// DeliveryTimelineNotNil applies the NotNil predicate on the "delivery_timeline" field.
func DeliveryTimelineNotNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotNull(FieldDeliveryTimeline))
}

// DeliveryTimelineEqualFold applies the EqualFold predicate on the "delivery_timeline" field.
func DeliveryTimelineEqualFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEqualFold(FieldDeliveryTimeline, v))
}

// DeliveryTimelineContainsFold applies the ContainsFold predicate on the "delivery_timeline" field.
func DeliveryTimelineContainsFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContainsFold(FieldDeliveryTimeline, v))
}

// RequiredQtyEQ applies the EQ predicate on the "required_qty" field.
func RequiredQtyEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldRequiredQty, v))
}

// RequiredQtyNEQ applies the NEQ predicate on the "required_qty" field.
func RequiredQtyNEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldRequiredQty, v))
}

// RequiredQtyIn applies the In predicate on the "required_qty" field.
func RequiredQtyIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldRequiredQty, vs...))
}

// RequiredQtyNotIn applies the NotIn predicate on the "required_qty" field.
func RequiredQtyNotIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldRequiredQty, vs...))
}

// RequiredQtyGT applies the GT predicate on the "required_qty" field.
func RequiredQtyGT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldRequiredQty, v))
}

// RequiredQtyGTE applies the GTE predicate on the "required_qty" field.
func RequiredQtyGTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldRequiredQty, v))
}

// RequiredQtyLT applies the LT predicate on the "required_qty" field.
func RequiredQtyLT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldRequiredQty, v))
}

// RequiredQtyLTE applies the LTE predicate on the "required_qty" field.
func RequiredQtyLTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldRequiredQty, v))
}

// SpareQtyEQ applies the EQ predicate on the "spare_qty" field.
func SpareQtyEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldSpareQty, v))
}

// SpareQtyNEQ applies the NEQ predicate on the "spare_qty" field.
func SpareQtyNEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldSpareQty, v))
}

// SpareQtyIn applies the In predicate on the "spare_qty" field.
func SpareQtyIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldSpareQty, vs...))
}

// SpareQtyNotIn applies the NotIn predicate on the "spare_qty" field.
func SpareQtyNotIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldSpareQty, vs...))
}

// SpareQtyGT applies the GT predicate on the "spare_qty" field.
func SpareQtyGT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldSpareQty, v))
}

// SpareQtyGTE applies the GTE predicate on the "spare_qty" field.
func SpareQtyGTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldSpareQty, v))
}

// SpareQtyLT applies the LT predicate on the "spare_qty" field.
func SpareQtyLT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldSpareQty, v))
}

// SpareQtyLTE applies the LTE predicate on the "spare_qty" field.
func SpareQtyLTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldSpareQty, v))
}

// AvailableStockEQ applies the EQ predicate on the "available_stock" field.
func AvailableStockEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldAvailableStock, v))
}

// AvailableStockNEQ applies the NEQ predicate on the "available_stock" field.
func AvailableStockNEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldAvailableStock, v))
}

// AvailableStockIn applies the In predicate on the "available_stock" field.
func AvailableStockIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldAvailableStock, vs...))
}

// AvailableStockNotIn applies the NotIn predicate on the "available_stock" field.
func AvailableStockNotIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldAvailableStock, vs...))
}

// AvailableStockGT applies the GT predicate on the "available_stock" field.
func AvailableStockGT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldAvailableStock, v))
}

// AvailableStockGTE applies the GTE predicate on the "available_stock" field.
func AvailableStockGTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldAvailableStock, v))
}

// AvailableStockLT applies the LT predicate on the "available_stock" field.
func AvailableStockLT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldAvailableStock, v))
}

// AvailableStockLTE applies the LTE predicate on the "available_stock" field.
func AvailableStockLTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldAvailableStock, v))
}

// PurchaseQtyEQ applies the EQ predicate on the "purchase_qty" field.
func PurchaseQtyEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldPurchaseQty, v))
}

// PurchaseQtyNEQ applies the NEQ predicate on the "purchase_qty" field.
func PurchaseQtyNEQ(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldPurchaseQty, v))
}

// PurchaseQtyIn applies the In predicate on the "purchase_qty" field.
func PurchaseQtyIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldPurchaseQty, vs...))
}

// PurchaseQtyNotIn applies the NotIn predicate on the "purchase_qty" field.
func PurchaseQtyNotIn(vs ...int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldPurchaseQty, vs...))
}

// PurchaseQtyGT applies the GT predicate on the "purchase_qty" field.
func PurchaseQtyGT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldPurchaseQty, v))
}

// PurchaseQtyGTE applies the GTE predicate on the "purchase_qty" field.
func PurchaseQtyGTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldPurchaseQty, v))
}

// PurchaseQtyLT applies the LT predicate on the "purchase_qty" field.
func PurchaseQtyLT(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldPurchaseQty, v))
}

// PurchaseQtyLTE applies the LTE predicate on the "purchase_qty" field.
func PurchaseQtyLTE(v int) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldPurchaseQty, v))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldUnitPrice, v))
}

// UnitPriceIsNil applies the IsNil predicate on the "unit_price" field.
func UnitPriceIsNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIsNull(FieldUnitPrice))
}

// UnitPriceNotNil applies the NotNil predicate on the "unit_price" field.
func UnitPriceNotNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotNull(FieldUnitPrice))
}

// TotalPriceEQ applies the EQ predicate on the "total_price" field.
func TotalPriceEQ(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldTotalPrice, v))
}

// TotalPriceNEQ applies the NEQ predicate on the "total_price" field.
func TotalPriceNEQ(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldTotalPrice, v))
}

// TotalPriceIn applies the In predicate on the "total_price" field.
func TotalPriceIn(vs ...float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldTotalPrice, vs...))
}

// TotalPriceNotIn applies the NotIn predicate on the "total_price" field.
func TotalPriceNotIn(vs ...float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldTotalPrice, vs...))
}

// TotalPriceGT applies the GT predicate on the "total_price" field.
func TotalPriceGT(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldTotalPrice, v))
}

// TotalPriceGTE applies the GTE predicate on the "total_price" field.
func TotalPriceGTE(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldTotalPrice, v))
}

// TotalPriceLT applies the LT predicate on the "total_price" field.
func TotalPriceLT(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldTotalPrice, v))
}

// TotalPriceLTE applies the LTE predicate on the "total_price" field.
func TotalPriceLTE(v float64) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldTotalPrice, v))
}

// TotalPriceIsNil applies the IsNil predicate on the "total_price" field.
func TotalPriceIsNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIsNull(FieldTotalPrice))
}

// TotalPriceNotNil applies the NotNil predicate on the "total_price" field.
func TotalPriceNotNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotNull(FieldTotalPrice))
}

// PurposeEQ applies the EQ predicate on the "purpose" field.
func PurposeEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldPurpose, v))
}

// PurposeNEQ applies the NEQ predicate on the "purpose" field.
func PurposeNEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldPurpose, v))
}

// PurposeIn applies the In predicate on the "purpose" field.
func PurposeIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldPurpose, vs...))
}

// PurposeNotIn applies the NotIn predicate on the "purpose" field.
func PurposeNotIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldPurpose, vs...))
}

// PurposeGT applies the GT predicate on the "purpose" field.
func PurposeGT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldPurpose, v))
}

// PurposeGTE applies the GTE predicate on the "purpose" field.
func PurposeGTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldPurpose, v))
}

// PurposeLT applies the LT predicate on the "purpose" field.
func PurposeLT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldPurpose, v))
}

// PurposeLTE applies the LTE predicate on the "purpose" field.
func PurposeLTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldPurpose, v))
}

// PurposeContains applies the Contains predicate on the "purpose" field.
func PurposeContains(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContains(FieldPurpose, v))
}

// PurposeHasPrefix applies the HasPrefix predicate on the "purpose" field.
func PurposeHasPrefix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasPrefix(FieldPurpose, v))
}

// PurposeHasSuffix applies the HasSuffix predicate on the "purpose" field.
func PurposeHasSuffix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasSuffix(FieldPurpose, v))
}

// PurposeIsNil applies the IsNil predicate on the "purpose" field.
func PurposeIsNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIsNull(FieldPurpose))
}

// PurposeNotNil applies the NotNil predicate on the "purpose" field.
func PurposeNotNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotNull(FieldPurpose))
}

// PurposeEqualFold applies the EqualFold predicate on the "purpose" field.
func PurposeEqualFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEqualFold(FieldPurpose, v))
}

// PurposeContainsFold applies the ContainsFold predicate on the "purpose" field.
func PurposeContainsFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContainsFold(FieldPurpose, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrderItem {
	return predicate.OrderItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPurchaseOrder applies the HasEdge predicate on the "purchase_order" edge.
func HasPurchaseOrder() predicate.OrderItem {
	return predicate.OrderItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PurchaseOrderTable, PurchaseOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPurchaseOrderWith applies the HasEdge predicate on the "purchase_order" edge with a given conditions (other predicates).
func HasPurchaseOrderWith(preds ...predicate.PurchaseOrder) predicate.OrderItem {
	return predicate.OrderItem(func(s *sql.Selector) {
		step := newPurchaseOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderItem) predicate.OrderItem {
	return predicate.OrderItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderItem) predicate.OrderItem {
	return predicate.OrderItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderItem) predicate.OrderItem {
	return predicate.OrderItem(sql.NotPredicates(p))
}
