// Code generated by ent, DO NOT EDIT.

package purchaseorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/your-org/atlas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldID, id))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldOrderNo, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldProject, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// OrderDate applies equality check predicate on the "order_date" field. It's identical to OrderDateEQ.
func OrderDate(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldOrderDate, v))
}

// ExpectedDate applies equality check predicate on the "expected_date" field. It's identical to ExpectedDateEQ.
func ExpectedDate(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldExpectedDate, v))
}

// DeliveryLocation applies equality check predicate on the "delivery_location" field. It's identical to DeliveryLocationEQ.
func DeliveryLocation(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldDeliveryLocation, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectIsNil applies the IsNil predicate on the "project" field.
func ProjectIsNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIsNull(FieldProject))
}

// ProjectNotNil applies the NotNil predicate on the "project" field.
func ProjectNotNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotNull(FieldProject))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContainsFold(FieldProject, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldTotalAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// OrderDateEQ applies the EQ predicate on the "order_date" field.
func OrderDateEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldOrderDate, v))
}

// OrderDateNEQ applies the NEQ predicate on the "order_date" field.
func OrderDateNEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldOrderDate, v))
}

// OrderDateIn applies the In predicate on the "order_date" field.
func OrderDateIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldOrderDate, vs...))
}

// OrderDateNotIn applies the NotIn predicate on the "order_date" field.
func OrderDateNotIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldOrderDate, vs...))
}

// OrderDateGT applies the GT predicate on the "order_date" field.
func OrderDateGT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldOrderDate, v))
}

// OrderDateGTE applies the GTE predicate on the "order_date" field.
func OrderDateGTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldOrderDate, v))
}

// OrderDateLT applies the LT predicate on the "order_date" field.
func OrderDateLT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldOrderDate, v))
}

// OrderDateLTE applies the LTE predicate on the "order_date" field.
func OrderDateLTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldOrderDate, v))
}

// OrderDateIsNil applies the IsNil predicate on the "order_date" field.
func OrderDateIsNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIsNull(FieldOrderDate))
}

// OrderDateNotNil applies the NotNil predicate on the "order_date" field.
func OrderDateNotNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotNull(FieldOrderDate))
}

// ExpectedDateEQ applies the EQ predicate on the "expected_date" field.
func ExpectedDateEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldExpectedDate, v))
}

// ExpectedDateNEQ applies the NEQ predicate on the "expected_date" field.
func ExpectedDateNEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldExpectedDate, v))
}

// ExpectedDateIn applies the In predicate on the "expected_date" field.
func ExpectedDateIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldExpectedDate, vs...))
}

// ExpectedDateNotIn applies the NotIn predicate on the "expected_date" field.
func ExpectedDateNotIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldExpectedDate, vs...))
}

// ExpectedDateGT applies the GT predicate on the "expected_date" field.
func ExpectedDateGT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldExpectedDate, v))
}

// ExpectedDateGTE applies the GTE predicate on the "expected_date" field.
func ExpectedDateGTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldExpectedDate, v))
}

// ExpectedDateLT applies the LT predicate on the "expected_date" field.
func ExpectedDateLT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldExpectedDate, v))
}

// ExpectedDateLTE applies the LTE predicate on the "expected_date" field.
func ExpectedDateLTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldExpectedDate, v))
}

// ExpectedDateIsNil applies the IsNil predicate on the "expected_date" field.
func ExpectedDateIsNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIsNull(FieldExpectedDate))
}

// ExpectedDateNotNil applies the NotNil predicate on the "expected_date" field.
func ExpectedDateNotNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotNull(FieldExpectedDate))
}

// DeliveryLocationEQ applies the EQ predicate on the "delivery_location" field.
func DeliveryLocationEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldDeliveryLocation, v))
}

// DeliveryLocationNEQ applies the NEQ predicate on the "delivery_location" field.
func DeliveryLocationNEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldDeliveryLocation, v))
}

// DeliveryLocationIn applies the In predicate on the "delivery_location" field.
func DeliveryLocationIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldDeliveryLocation, vs...))
}

// DeliveryLocationNotIn applies the NotIn predicate on the "delivery_location" field.
func DeliveryLocationNotIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldDeliveryLocation, vs...))
}

// DeliveryLocationGT applies the GT predicate on the "delivery_location" field.
func DeliveryLocationGT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldDeliveryLocation, v))
}

// DeliveryLocationGTE applies the GTE predicate on the "delivery_location" field.
func DeliveryLocationGTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldDeliveryLocation, v))
}

// DeliveryLocationLT applies the LT predicate on the "delivery_location" field.
func DeliveryLocationLT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldDeliveryLocation, v))
}

// DeliveryLocationLTE applies the LTE predicate on the "delivery_location" field.
func DeliveryLocationLTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldDeliveryLocation, v))
}

// DeliveryLocationContains applies the Contains predicate on the "delivery_location" field.
func DeliveryLocationContains(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContains(FieldDeliveryLocation, v))
}

// DeliveryLocationHasPrefix applies the HasPrefix predicate on the "delivery_location" field.
func DeliveryLocationHasPrefix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasPrefix(FieldDeliveryLocation, v))
}

// DeliveryLocationHasSuffix applies the HasSuffix predicate on the "delivery_location" field.
func DeliveryLocationHasSuffix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasSuffix(FieldDeliveryLocation, v))
}

// DeliveryLocationIsNil applies the IsNil predicate on the "delivery_location" field.
func DeliveryLocationIsNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIsNull(FieldDeliveryLocation))
}

// DeliveryLocationNotNil applies the NotNil predicate on the "delivery_location" field.
func DeliveryLocationNotNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotNull(FieldDeliveryLocation))
}

// DeliveryLocationEqualFold applies the EqualFold predicate on the "delivery_location" field.
func DeliveryLocationEqualFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEqualFold(FieldDeliveryLocation, v))
}

// DeliveryLocationContainsFold applies the ContainsFold predicate on the "delivery_location" field.
func DeliveryLocationContainsFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContainsFold(FieldDeliveryLocation, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSupplier applies the HasEdge predicate on the "supplier" edge.
func HasSupplier() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SupplierTable, SupplierColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSupplierWith applies the HasEdge predicate on the "supplier" edge with a given conditions (other predicates).
func HasSupplierWith(preds ...predicate.Supplier) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := newSupplierStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.OrderItem) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApproval applies the HasEdge predicate on the "approval" edge.
func HasApproval() predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ApprovalTable, ApprovalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApprovalWith applies the HasEdge predicate on the "approval" edge with a given conditions (other predicates).
func HasApprovalWith(preds ...predicate.Approval) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(func(s *sql.Selector) {
		step := newApprovalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PurchaseOrder) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PurchaseOrder) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PurchaseOrder) predicate.PurchaseOrder {
	return predicate.PurchaseOrder(sql.NotPredicates(p))
}
