// Code generated by ent, DO NOT EDIT.

package networkconnection

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the networkconnection type in the database.
	Label = "network_connection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourcePort holds the string denoting the source_port field in the database.
	FieldSourcePort = "source_port"
	// FieldTargetPort holds the string denoting the target_port field in the database.
	FieldTargetPort = "target_port"
	// FieldConnectionType holds the string denoting the connection_type field in the database.
	FieldConnectionType = "connection_type"
	// FieldSpeed holds the string denoting the speed field in the database.
	FieldSpeed = "speed"
	// FieldCableType holds the string denoting the cable_type field in the database.
	FieldCableType = "cable_type"
	// FieldCableLength holds the string denoting the cable_length field in the database.
	FieldCableLength = "cable_length"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSourceEquipment holds the string denoting the source_equipment edge name in mutations.
	EdgeSourceEquipment = "source_equipment"
	// EdgeTargetEquipment holds the string denoting the target_equipment edge name in mutations.
	EdgeTargetEquipment = "target_equipment"
	// Table holds the table name of the networkconnection in the database.
	Table = "network_connections"
	// SourceEquipmentTable is the table that holds the source_equipment relation/edge.
	SourceEquipmentTable = "network_connections"
	// SourceEquipmentInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	SourceEquipmentInverseTable = "assets"
	// SourceEquipmentColumn is the table column denoting the source_equipment relation/edge.
	SourceEquipmentColumn = "asset_network_connections_source"
	// TargetEquipmentTable is the table that holds the target_equipment relation/edge.
	TargetEquipmentTable = "network_connections"
	// TargetEquipmentInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	TargetEquipmentInverseTable = "assets"
	// TargetEquipmentColumn is the table column denoting the target_equipment relation/edge.
	TargetEquipmentColumn = "asset_network_connections_target"
)

// Columns holds all SQL columns for networkconnection fields.
var Columns = []string{
	FieldID,
	FieldSourcePort,
	FieldTargetPort,
	FieldConnectionType,
	FieldSpeed,
	FieldCableType,
	FieldCableLength,
	FieldStatus,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "network_connections"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"asset_network_connections_source",
	"asset_network_connections_target",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// SourcePortValidator is a validator for the "source_port" field. It is called by the builders before save.
	SourcePortValidator func(string) error
	// TargetPortValidator is a validator for the "target_port" field. It is called by the builders before save.
	TargetPortValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// ConnectionType defines the type for the "connection_type" enum field.
type ConnectionType string

// ConnectionTypeEthernet is the default value of the ConnectionType enum.
const DefaultConnectionType = ConnectionTypeEthernet

// ConnectionType values.
const (
	ConnectionTypeEthernet   ConnectionType = "ethernet"
	ConnectionTypeInfiniband ConnectionType = "infiniband"
	ConnectionTypeFiber      ConnectionType = "fiber"
	ConnectionTypeOther      ConnectionType = "other"
)

func (ct ConnectionType) String() string {
	return string(ct)
}

// ConnectionTypeValidator is a validator for the "connection_type" field enum values. It is called by the builders before save.
func ConnectionTypeValidator(ct ConnectionType) error {
	switch ct {
	case ConnectionTypeEthernet, ConnectionTypeInfiniband, ConnectionTypeFiber, ConnectionTypeOther:
		return nil
	default:
		return fmt.Errorf("networkconnection: invalid enum value for connection_type field: %q", ct)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive      Status = "active"
	StatusInactive    Status = "inactive"
	StatusMaintenance Status = "maintenance"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusMaintenance:
		return nil
	default:
		return fmt.Errorf("networkconnection: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the NetworkConnection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourcePort orders the results by the source_port field.
func BySourcePort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePort, opts...).ToFunc()
}

// ByTargetPort orders the results by the target_port field.
func ByTargetPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetPort, opts...).ToFunc()
}

// ByConnectionType orders the results by the connection_type field.
func ByConnectionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionType, opts...).ToFunc()
}

// BySpeed orders the results by the speed field.
func BySpeed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpeed, opts...).ToFunc()
}

// ByCableType orders the results by the cable_type field.
func ByCableType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCableType, opts...).ToFunc()
}

// ByCableLength orders the results by the cable_length field.
func ByCableLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCableLength, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySourceEquipmentField orders the results by source_equipment field.
func BySourceEquipmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceEquipmentStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetEquipmentField orders the results by target_equipment field.
func ByTargetEquipmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetEquipmentStep(), sql.OrderByField(field, opts...))
	}
}
func newSourceEquipmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceEquipmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceEquipmentTable, SourceEquipmentColumn),
	)
}
func newTargetEquipmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetEquipmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetEquipmentTable, TargetEquipmentColumn),
	)
}
