// Code generated by ent, DO NOT EDIT.

package networkconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/your-org/atlas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldID, id))
}

// SourcePort applies equality check predicate on the "source_port" field. It's identical to SourcePortEQ.
func SourcePort(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldSourcePort, v))
}

// TargetPort applies equality check predicate on the "target_port" field. It's identical to TargetPortEQ.
func TargetPort(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldTargetPort, v))
}

// Speed applies equality check predicate on the "speed" field. It's identical to SpeedEQ.
func Speed(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldSpeed, v))
}

// CableType applies equality check predicate on the "cable_type" field. It's identical to CableTypeEQ.
func CableType(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldCableType, v))
}

// CableLength applies equality check predicate on the "cable_length" field. It's identical to CableLengthEQ.
func CableLength(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldCableLength, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourcePortEQ applies the EQ predicate on the "source_port" field.
func SourcePortEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldSourcePort, v))
}

// SourcePortNEQ applies the NEQ predicate on the "source_port" field.
func SourcePortNEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldSourcePort, v))
}

// SourcePortIn applies the In predicate on the "source_port" field.
func SourcePortIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldSourcePort, vs...))
}

// SourcePortNotIn applies the NotIn predicate on the "source_port" field.
func SourcePortNotIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldSourcePort, vs...))
}

// SourcePortGT applies the GT predicate on the "source_port" field.
func SourcePortGT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldSourcePort, v))
}

// SourcePortGTE applies the GTE predicate on the "source_port" field.
func SourcePortGTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldSourcePort, v))
}

// SourcePortLT applies the LT predicate on the "source_port" field.
func SourcePortLT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldSourcePort, v))
}

// SourcePortLTE applies the LTE predicate on the "source_port" field.
func SourcePortLTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldSourcePort, v))
}

// SourcePortContains applies the Contains predicate on the "source_port" field.
func SourcePortContains(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContains(FieldSourcePort, v))
}

// SourcePortHasPrefix applies the HasPrefix predicate on the "source_port" field.
func SourcePortHasPrefix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasPrefix(FieldSourcePort, v))
}

// SourcePortHasSuffix applies the HasSuffix predicate on the "source_port" field.
func SourcePortHasSuffix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasSuffix(FieldSourcePort, v))
}

// SourcePortEqualFold applies the EqualFold predicate on the "source_port" field.
func SourcePortEqualFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEqualFold(FieldSourcePort, v))
}

// SourcePortContainsFold applies the ContainsFold predicate on the "source_port" field.
func SourcePortContainsFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContainsFold(FieldSourcePort, v))
}

// TargetPortEQ applies the EQ predicate on the "target_port" field.
func TargetPortEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldTargetPort, v))
}

// TargetPortNEQ applies the NEQ predicate on the "target_port" field.
func TargetPortNEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldTargetPort, v))
}

// TargetPortIn applies the In predicate on the "target_port" field.
func TargetPortIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldTargetPort, vs...))
}

// TargetPortNotIn applies the NotIn predicate on the "target_port" field.
func TargetPortNotIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldTargetPort, vs...))
}

// TargetPortGT applies the GT predicate on the "target_port" field.
func TargetPortGT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldTargetPort, v))
}

// TargetPortGTE applies the GTE predicate on the "target_port" field.
func TargetPortGTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldTargetPort, v))
}

// TargetPortLT applies the LT predicate on the "target_port" field.
func TargetPortLT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldTargetPort, v))
}

// TargetPortLTE applies the LTE predicate on the "target_port" field.
func TargetPortLTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldTargetPort, v))
}

// TargetPortContains applies the Contains predicate on the "target_port" field.
func TargetPortContains(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContains(FieldTargetPort, v))
}

// TargetPortHasPrefix applies the HasPrefix predicate on the "target_port" field.
func TargetPortHasPrefix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasPrefix(FieldTargetPort, v))
}

// TargetPortHasSuffix applies the HasSuffix predicate on the "target_port" field.
func TargetPortHasSuffix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasSuffix(FieldTargetPort, v))
}

// TargetPortEqualFold applies the EqualFold predicate on the "target_port" field.
func TargetPortEqualFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEqualFold(FieldTargetPort, v))
}

// TargetPortContainsFold applies the ContainsFold predicate on the "target_port" field.
func TargetPortContainsFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContainsFold(FieldTargetPort, v))
}

// ConnectionTypeEQ applies the EQ predicate on the "connection_type" field.
func ConnectionTypeEQ(v ConnectionType) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldConnectionType, v))
}

// ConnectionTypeNEQ applies the NEQ predicate on the "connection_type" field.
func ConnectionTypeNEQ(v ConnectionType) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldConnectionType, v))
}

// ConnectionTypeIn applies the In predicate on the "connection_type" field.
func ConnectionTypeIn(vs ...ConnectionType) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldConnectionType, vs...))
}

// ConnectionTypeNotIn applies the NotIn predicate on the "connection_type" field.
func ConnectionTypeNotIn(vs ...ConnectionType) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldConnectionType, vs...))
}

// SpeedEQ applies the EQ predicate on the "speed" field.
func SpeedEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldSpeed, v))
}

// SpeedNEQ applies the NEQ predicate on the "speed" field.
func SpeedNEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldSpeed, v))
}

// SpeedIn applies the In predicate on the "speed" field.
func SpeedIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldSpeed, vs...))
}

// SpeedNotIn applies the NotIn predicate on the "speed" field.
func SpeedNotIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldSpeed, vs...))
}

// SpeedGT applies the GT predicate on the "speed" field.
func SpeedGT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldSpeed, v))
}

// SpeedGTE applies the GTE predicate on the "speed" field.
func SpeedGTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldSpeed, v))
}

// SpeedLT applies the LT predicate on the "speed" field.
func SpeedLT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldSpeed, v))
}

// SpeedLTE applies the LTE predicate on the "speed" field.
func SpeedLTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldSpeed, v))
}

// SpeedContains applies the Contains predicate on the "speed" field.
func SpeedContains(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContains(FieldSpeed, v))
}

// SpeedHasPrefix applies the HasPrefix predicate on the "speed" field.
func SpeedHasPrefix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasPrefix(FieldSpeed, v))
}

// SpeedHasSuffix applies the HasSuffix predicate on the "speed" field.
func SpeedHasSuffix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasSuffix(FieldSpeed, v))
}

// SpeedIsNil applies the IsNil predicate on the "speed" field.
func SpeedIsNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIsNull(FieldSpeed))
}

// SpeedNotNil applies the NotNil predicate on the "speed" field.
func SpeedNotNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotNull(FieldSpeed))
}

// SpeedEqualFold applies the EqualFold predicate on the "speed" field.
func SpeedEqualFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEqualFold(FieldSpeed, v))
}

// SpeedContainsFold applies the ContainsFold predicate on the "speed" field.
func SpeedContainsFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContainsFold(FieldSpeed, v))
}

// CableTypeEQ applies the EQ predicate on the "cable_type" field.
func CableTypeEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldCableType, v))
}

// CableTypeNEQ applies the NEQ predicate on the "cable_type" field.
func CableTypeNEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldCableType, v))
}

// CableTypeIn applies the In predicate on the "cable_type" field.
func CableTypeIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldCableType, vs...))
}

// CableTypeNotIn applies the NotIn predicate on the "cable_type" field.
func CableTypeNotIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldCableType, vs...))
}

// CableTypeGT applies the GT predicate on the "cable_type" field.
func CableTypeGT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldCableType, v))
}

// CableTypeGTE applies the GTE predicate on the "cable_type" field.
func CableTypeGTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldCableType, v))
}

// CableTypeLT applies the LT predicate on the "cable_type" field.
func CableTypeLT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldCableType, v))
}

// CableTypeLTE applies the LTE predicate on the "cable_type" field.
func CableTypeLTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldCableType, v))
}

// CableTypeContains applies the Contains predicate on the "cable_type" field.
func CableTypeContains(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContains(FieldCableType, v))
}

// CableTypeHasPrefix applies the HasPrefix predicate on the "cable_type" field.
func CableTypeHasPrefix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasPrefix(FieldCableType, v))
}

// CableTypeHasSuffix applies the HasSuffix predicate on the "cable_type" field.
func CableTypeHasSuffix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasSuffix(FieldCableType, v))
}

// CableTypeIsNil applies the IsNil predicate on the "cable_type" field.
func CableTypeIsNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIsNull(FieldCableType))
}

// CableTypeNotNil applies the NotNil predicate on the "cable_type" field.
func CableTypeNotNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotNull(FieldCableType))
}

// CableTypeEqualFold applies the EqualFold predicate on the "cable_type" field.
func CableTypeEqualFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEqualFold(FieldCableType, v))
}

// CableTypeContainsFold applies the ContainsFold predicate on the "cable_type" field.
func CableTypeContainsFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContainsFold(FieldCableType, v))
}

// CableLengthEQ applies the EQ predicate on the "cable_length" field.
func CableLengthEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldCableLength, v))
}

// CableLengthNEQ applies the NEQ predicate on the "cable_length" field.
func CableLengthNEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldCableLength, v))
}

// CableLengthIn applies the In predicate on the "cable_length" field.
func CableLengthIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldCableLength, vs...))
}

// CableLengthNotIn applies the NotIn predicate on the "cable_length" field.
func CableLengthNotIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldCableLength, vs...))
}

// CableLengthGT applies the GT predicate on the "cable_length" field.
func CableLengthGT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldCableLength, v))
}

// CableLengthGTE applies the GTE predicate on the "cable_length" field.
func CableLengthGTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldCableLength, v))
}

// CableLengthLT applies the LT predicate on the "cable_length" field.
func CableLengthLT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldCableLength, v))
}

// CableLengthLTE applies the LTE predicate on the "cable_length" field.
func CableLengthLTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldCableLength, v))
}

// CableLengthContains applies the Contains predicate on the "cable_length" field.
func CableLengthContains(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContains(FieldCableLength, v))
}

// CableLengthHasPrefix applies the HasPrefix predicate on the "cable_length" field.
func CableLengthHasPrefix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasPrefix(FieldCableLength, v))
}

// CableLengthHasSuffix applies the HasSuffix predicate on the "cable_length" field.
func CableLengthHasSuffix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasSuffix(FieldCableLength, v))
}

// CableLengthIsNil applies the IsNil predicate on the "cable_length" field.
func CableLengthIsNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIsNull(FieldCableLength))
}

// CableLengthNotNil applies the NotNil predicate on the "cable_length" field.
func CableLengthNotNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotNull(FieldCableLength))
}

// CableLengthEqualFold applies the EqualFold predicate on the "cable_length" field.
func CableLengthEqualFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEqualFold(FieldCableLength, v))
}

// CableLengthContainsFold applies the ContainsFold predicate on the "cable_length" field.
func CableLengthContainsFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContainsFold(FieldCableLength, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldStatus, vs...))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSourceEquipment applies the HasEdge predicate on the "source_equipment" edge.
func HasSourceEquipment() predicate.NetworkConnection {
	return predicate.NetworkConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceEquipmentTable, SourceEquipmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceEquipmentWith applies the HasEdge predicate on the "source_equipment" edge with a given conditions (other predicates).
func HasSourceEquipmentWith(preds ...predicate.Asset) predicate.NetworkConnection {
	return predicate.NetworkConnection(func(s *sql.Selector) {
		step := newSourceEquipmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetEquipment applies the HasEdge predicate on the "target_equipment" edge.
func HasTargetEquipment() predicate.NetworkConnection {
	return predicate.NetworkConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetEquipmentTable, TargetEquipmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetEquipmentWith applies the HasEdge predicate on the "target_equipment" edge with a given conditions (other predicates).
func HasTargetEquipmentWith(preds ...predicate.Asset) predicate.NetworkConnection {
	return predicate.NetworkConnection(func(s *sql.Selector) {
		step := newTargetEquipmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NetworkConnection) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NetworkConnection) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NetworkConnection) predicate.NetworkConnection {
	return predicate.NetworkConnection(sql.NotPredicates(p))
}
