// Code generated by ent, DO NOT EDIT.

package approval

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the approval type in the database.
	Label = "approval"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldApprovalNo holds the string denoting the approval_no field in the database.
	FieldApprovalNo = "approval_no"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entity_type"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCurrentNode holds the string denoting the current_node field in the database.
	FieldCurrentNode = "current_node"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNodes holds the string denoting the nodes edge name in mutations.
	EdgeNodes = "nodes"
	// EdgeInitiator holds the string denoting the initiator edge name in mutations.
	EdgeInitiator = "initiator"
	// EdgePurchaseOrder holds the string denoting the purchase_order edge name in mutations.
	EdgePurchaseOrder = "purchase_order"
	// Table holds the table name of the approval in the database.
	Table = "approvals"
	// NodesTable is the table that holds the nodes relation/edge.
	NodesTable = "approval_nodes"
	// NodesInverseTable is the table name for the ApprovalNode entity.
	// It exists in this package in order to avoid circular dependency with the "approvalnode" package.
	NodesInverseTable = "approval_nodes"
	// NodesColumn is the table column denoting the nodes relation/edge.
	NodesColumn = "approval_nodes"
	// InitiatorTable is the table that holds the initiator relation/edge.
	InitiatorTable = "approvals"
	// InitiatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InitiatorInverseTable = "users"
	// InitiatorColumn is the table column denoting the initiator relation/edge.
	InitiatorColumn = "user_initiated_approvals"
	// PurchaseOrderTable is the table that holds the purchase_order relation/edge.
	PurchaseOrderTable = "approvals"
	// PurchaseOrderInverseTable is the table name for the PurchaseOrder entity.
	// It exists in this package in order to avoid circular dependency with the "purchaseorder" package.
	PurchaseOrderInverseTable = "purchase_orders"
	// PurchaseOrderColumn is the table column denoting the purchase_order relation/edge.
	PurchaseOrderColumn = "purchase_order_approval"
)

// Columns holds all SQL columns for approval fields.
var Columns = []string{
	FieldID,
	FieldApprovalNo,
	FieldEntityType,
	FieldEntityID,
	FieldStatus,
	FieldCurrentNode,
	FieldNote,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "approvals"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"purchase_order_approval",
	"user_initiated_approvals",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ApprovalNoValidator is a validator for the "approval_no" field. It is called by the builders before save.
	ApprovalNoValidator func(string) error
	// EntityTypeValidator is a validator for the "entity_type" field. It is called by the builders before save.
	EntityTypeValidator func(string) error
	// DefaultCurrentNode holds the default value on creation for the "current_node" field.
	DefaultCurrentNode int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusApproved  Status = "approved"
	StatusRejected  Status = "rejected"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusApproved, StatusRejected, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("approval: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Approval queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByApprovalNo orders the results by the approval_no field.
func ByApprovalNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovalNo, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCurrentNode orders the results by the current_node field.
func ByCurrentNode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentNode, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNodesCount orders the results by nodes count.
func ByNodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNodesStep(), opts...)
	}
}

// ByNodes orders the results by nodes terms.
func ByNodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInitiatorField orders the results by initiator field.
func ByInitiatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInitiatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByPurchaseOrderField orders the results by purchase_order field.
func ByPurchaseOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPurchaseOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newNodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NodesTable, NodesColumn),
	)
}
func newInitiatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InitiatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InitiatorTable, InitiatorColumn),
	)
}
func newPurchaseOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PurchaseOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, PurchaseOrderTable, PurchaseOrderColumn),
	)
}
