// Code generated by ent, DO NOT EDIT.

package approval

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/your-org/atlas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldID, id))
}

// ApprovalNo applies equality check predicate on the "approval_no" field. It's identical to ApprovalNoEQ.
func ApprovalNo(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldApprovalNo, v))
}

// EntityType applies equality check predicate on the "entity_type" field. It's identical to EntityTypeEQ.
func EntityType(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldEntityType, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldEntityID, v))
}

// CurrentNode applies equality check predicate on the "current_node" field. It's identical to CurrentNodeEQ.
func CurrentNode(v int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldCurrentNode, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldUpdatedAt, v))
}

// ApprovalNoEQ applies the EQ predicate on the "approval_no" field.
func ApprovalNoEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldApprovalNo, v))
}

// ApprovalNoNEQ applies the NEQ predicate on the "approval_no" field.
func ApprovalNoNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldApprovalNo, v))
}

// ApprovalNoIn applies the In predicate on the "approval_no" field.
func ApprovalNoIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldApprovalNo, vs...))
}

// ApprovalNoNotIn applies the NotIn predicate on the "approval_no" field.
func ApprovalNoNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldApprovalNo, vs...))
}

// ApprovalNoGT applies the GT predicate on the "approval_no" field.
func ApprovalNoGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldApprovalNo, v))
}

// ApprovalNoGTE applies the GTE predicate on the "approval_no" field.
func ApprovalNoGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldApprovalNo, v))
}

// ApprovalNoLT applies the LT predicate on the "approval_no" field.
func ApprovalNoLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldApprovalNo, v))
}

// ApprovalNoLTE applies the LTE predicate on the "approval_no" field.
func ApprovalNoLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldApprovalNo, v))
}

// ApprovalNoContains applies the Contains predicate on the "approval_no" field.
func ApprovalNoContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldApprovalNo, v))
}

// ApprovalNoHasPrefix applies the HasPrefix predicate on the "approval_no" field.
func ApprovalNoHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldApprovalNo, v))
}

// ApprovalNoHasSuffix applies the HasSuffix predicate on the "approval_no" field.
func ApprovalNoHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldApprovalNo, v))
}

// ApprovalNoEqualFold applies the EqualFold predicate on the "approval_no" field.
func ApprovalNoEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldApprovalNo, v))
}

// ApprovalNoContainsFold applies the ContainsFold predicate on the "approval_no" field.
func ApprovalNoContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldApprovalNo, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldEntityType, v))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldEntityType, v))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldEntityType, vs...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldEntityType, vs...))
}

// EntityTypeGT applies the GT predicate on the "entity_type" field.
func EntityTypeGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldEntityType, v))
}

// EntityTypeGTE applies the GTE predicate on the "entity_type" field.
func EntityTypeGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldEntityType, v))
}

// EntityTypeLT applies the LT predicate on the "entity_type" field.
func EntityTypeLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldEntityType, v))
}

// EntityTypeLTE applies the LTE predicate on the "entity_type" field.
func EntityTypeLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldEntityType, v))
}

// EntityTypeContains applies the Contains predicate on the "entity_type" field.
func EntityTypeContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldEntityType, v))
}

// EntityTypeHasPrefix applies the HasPrefix predicate on the "entity_type" field.
func EntityTypeHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldEntityType, v))
}

// EntityTypeHasSuffix applies the HasSuffix predicate on the "entity_type" field.
func EntityTypeHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldEntityType, v))
}

// EntityTypeEqualFold applies the EqualFold predicate on the "entity_type" field.
func EntityTypeEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldEntityType, v))
}

// EntityTypeContainsFold applies the ContainsFold predicate on the "entity_type" field.
func EntityTypeContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldEntityType, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v int) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...int) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...int) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v int) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v int) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v int) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v int) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldEntityID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldStatus, vs...))
}

// CurrentNodeEQ applies the EQ predicate on the "current_node" field.
func CurrentNodeEQ(v int) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldCurrentNode, v))
}

// CurrentNodeNEQ applies the NEQ predicate on the "current_node" field.
func CurrentNodeNEQ(v int) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldCurrentNode, v))
}

// CurrentNodeIn applies the In predicate on the "current_node" field.
func CurrentNodeIn(vs ...int) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldCurrentNode, vs...))
}

// CurrentNodeNotIn applies the NotIn predicate on the "current_node" field.
func CurrentNodeNotIn(vs ...int) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldCurrentNode, vs...))
}

// CurrentNodeGT applies the GT predicate on the "current_node" field.
func CurrentNodeGT(v int) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldCurrentNode, v))
}

// CurrentNodeGTE applies the GTE predicate on the "current_node" field.
func CurrentNodeGTE(v int) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldCurrentNode, v))
}

// CurrentNodeLT applies the LT predicate on the "current_node" field.
func CurrentNodeLT(v int) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldCurrentNode, v))
}

// CurrentNodeLTE applies the LTE predicate on the "current_node" field.
func CurrentNodeLTE(v int) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldCurrentNode, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Approval {
	return predicate.Approval(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Approval {
	return predicate.Approval(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Approval {
	return predicate.Approval(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Approval {
	return predicate.Approval(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Approval {
	return predicate.Approval(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasNodes applies the HasEdge predicate on the "nodes" edge.
func HasNodes() predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodesTable, NodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodesWith applies the HasEdge predicate on the "nodes" edge with a given conditions (other predicates).
func HasNodesWith(preds ...predicate.ApprovalNode) predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := newNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInitiator applies the HasEdge predicate on the "initiator" edge.
func HasInitiator() predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InitiatorTable, InitiatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInitiatorWith applies the HasEdge predicate on the "initiator" edge with a given conditions (other predicates).
func HasInitiatorWith(preds ...predicate.User) predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := newInitiatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPurchaseOrder applies the HasEdge predicate on the "purchase_order" edge.
func HasPurchaseOrder() predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PurchaseOrderTable, PurchaseOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPurchaseOrderWith applies the HasEdge predicate on the "purchase_order" edge with a given conditions (other predicates).
func HasPurchaseOrderWith(preds ...predicate.PurchaseOrder) predicate.Approval {
	return predicate.Approval(func(s *sql.Selector) {
		step := newPurchaseOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Approval) predicate.Approval {
	return predicate.Approval(sql.NotPredicates(p))
}
