// Code generated by ent, DO NOT EDIT.

package room

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldFloor holds the string denoting the floor field in the database.
	FieldFloor = "floor"
	// FieldArea holds the string denoting the area field in the database.
	FieldArea = "area"
	// FieldPowerCapacity holds the string denoting the power_capacity field in the database.
	FieldPowerCapacity = "power_capacity"
	// FieldPowerUsed holds the string denoting the power_used field in the database.
	FieldPowerUsed = "power_used"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLayoutData holds the string denoting the layout_data field in the database.
	FieldLayoutData = "layout_data"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDataCenter holds the string denoting the data_center edge name in mutations.
	EdgeDataCenter = "data_center"
	// EdgeRacks holds the string denoting the racks edge name in mutations.
	EdgeRacks = "racks"
	// Table holds the table name of the room in the database.
	Table = "rooms"
	// DataCenterTable is the table that holds the data_center relation/edge.
	DataCenterTable = "rooms"
	// DataCenterInverseTable is the table name for the DataCenter entity.
	// It exists in this package in order to avoid circular dependency with the "datacenter" package.
	DataCenterInverseTable = "data_centers"
	// DataCenterColumn is the table column denoting the data_center relation/edge.
	DataCenterColumn = "data_center_rooms"
	// RacksTable is the table that holds the racks relation/edge.
	RacksTable = "racks"
	// RacksInverseTable is the table name for the Rack entity.
	// It exists in this package in order to avoid circular dependency with the "rack" package.
	RacksInverseTable = "racks"
	// RacksColumn is the table column denoting the racks relation/edge.
	RacksColumn = "room_racks"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCode,
	FieldFloor,
	FieldArea,
	FieldPowerCapacity,
	FieldPowerUsed,
	FieldStatus,
	FieldLayoutData,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "rooms"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"data_center_rooms",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultPowerUsed holds the default value on creation for the "power_used" field.
	DefaultPowerUsed float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive      Status = "active"
	StatusInactive    Status = "inactive"
	StatusMaintenance Status = "maintenance"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusMaintenance:
		return nil
	default:
		return fmt.Errorf("room: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Room queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByFloor orders the results by the floor field.
func ByFloor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFloor, opts...).ToFunc()
}

// ByArea orders the results by the area field.
func ByArea(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArea, opts...).ToFunc()
}

// ByPowerCapacity orders the results by the power_capacity field.
func ByPowerCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPowerCapacity, opts...).ToFunc()
}

// ByPowerUsed orders the results by the power_used field.
func ByPowerUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPowerUsed, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDataCenterField orders the results by data_center field.
func ByDataCenterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDataCenterStep(), sql.OrderByField(field, opts...))
	}
}

// ByRacksCount orders the results by racks count.
func ByRacksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRacksStep(), opts...)
	}
}

// ByRacks orders the results by racks terms.
func ByRacks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRacksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDataCenterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DataCenterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DataCenterTable, DataCenterColumn),
	)
}
func newRacksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RacksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RacksTable, RacksColumn),
	)
}
