// Code generated by ent, DO NOT EDIT.

package ipaddress

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ipaddress type in the database.
	Label = "ip_address"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldSubnet holds the string denoting the subnet field in the database.
	FieldSubnet = "subnet"
	// FieldGateway holds the string denoting the gateway field in the database.
	FieldGateway = "gateway"
	// FieldIPType holds the string denoting the ip_type field in the database.
	FieldIPType = "ip_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVlan holds the string denoting the vlan field in the database.
	FieldVlan = "vlan"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldAllocatedAt holds the string denoting the allocated_at field in the database.
	FieldAllocatedAt = "allocated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAsset holds the string denoting the asset edge name in mutations.
	EdgeAsset = "asset"
	// Table holds the table name of the ipaddress in the database.
	Table = "ip_addresses"
	// AssetTable is the table that holds the asset relation/edge.
	AssetTable = "ip_addresses"
	// AssetInverseTable is the table name for the Asset entity.
	// It exists in this package in order to avoid circular dependency with the "asset" package.
	AssetInverseTable = "assets"
	// AssetColumn is the table column denoting the asset relation/edge.
	AssetColumn = "asset_ip_addresses"
)

// Columns holds all SQL columns for ipaddress fields.
var Columns = []string{
	FieldID,
	FieldIPAddress,
	FieldSubnet,
	FieldGateway,
	FieldIPType,
	FieldStatus,
	FieldVlan,
	FieldNotes,
	FieldAllocatedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ip_addresses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"asset_ip_addresses",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	IPAddressValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// IPType defines the type for the "ip_type" enum field.
type IPType string

// IPTypeInternal is the default value of the IPType enum.
const DefaultIPType = IPTypeInternal

// IPType values.
const (
	IPTypeInternal   IPType = "internal"
	IPTypePublic     IPType = "public"
	IPTypeManagement IPType = "management"
)

func (it IPType) String() string {
	return string(it)
}

// IPTypeValidator is a validator for the "ip_type" field enum values. It is called by the builders before save.
func IPTypeValidator(it IPType) error {
	switch it {
	case IPTypeInternal, IPTypePublic, IPTypeManagement:
		return nil
	default:
		return fmt.Errorf("ipaddress: invalid enum value for ip_type field: %q", it)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusAvailable is the default value of the Status enum.
const DefaultStatus = StatusAvailable

// Status values.
const (
	StatusAllocated Status = "allocated"
	StatusAvailable Status = "available"
	StatusReserved  Status = "reserved"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAllocated, StatusAvailable, StatusReserved:
		return nil
	default:
		return fmt.Errorf("ipaddress: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the IPAddress queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// BySubnet orders the results by the subnet field.
func BySubnet(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubnet, opts...).ToFunc()
}

// ByGateway orders the results by the gateway field.
func ByGateway(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGateway, opts...).ToFunc()
}

// ByIPType orders the results by the ip_type field.
func ByIPType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVlan orders the results by the vlan field.
func ByVlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlan, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByAllocatedAt orders the results by the allocated_at field.
func ByAllocatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllocatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAssetField orders the results by asset field.
func ByAssetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetStep(), sql.OrderByField(field, opts...))
	}
}
func newAssetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssetTable, AssetColumn),
	)
}
