// Code generated by ent, DO NOT EDIT.

package ipaddress

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/your-org/atlas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldID, id))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldIPAddress, v))
}

// Subnet applies equality check predicate on the "subnet" field. It's identical to SubnetEQ.
func Subnet(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldSubnet, v))
}

// Gateway applies equality check predicate on the "gateway" field. It's identical to GatewayEQ.
func Gateway(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldGateway, v))
}

// Vlan applies equality check predicate on the "vlan" field. It's identical to VlanEQ.
func Vlan(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldVlan, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldNotes, v))
}

// AllocatedAt applies equality check predicate on the "allocated_at" field. It's identical to AllocatedAtEQ.
func AllocatedAt(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldAllocatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContainsFold(FieldIPAddress, v))
}

// SubnetEQ applies the EQ predicate on the "subnet" field.
func SubnetEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldSubnet, v))
}

// SubnetNEQ applies the NEQ predicate on the "subnet" field.
func SubnetNEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldSubnet, v))
}

// SubnetIn applies the In predicate on the "subnet" field.
func SubnetIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldSubnet, vs...))
}

// SubnetNotIn applies the NotIn predicate on the "subnet" field.
func SubnetNotIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldSubnet, vs...))
}

// SubnetGT applies the GT predicate on the "subnet" field.
func SubnetGT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldSubnet, v))
}

// SubnetGTE applies the GTE predicate on the "subnet" field.
func SubnetGTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldSubnet, v))
}

// SubnetLT applies the LT predicate on the "subnet" field.
func SubnetLT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldSubnet, v))
}

// SubnetLTE applies the LTE predicate on the "subnet" field.
func SubnetLTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldSubnet, v))
}

// SubnetContains applies the Contains predicate on the "subnet" field.
func SubnetContains(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContains(FieldSubnet, v))
}

// SubnetHasPrefix applies the HasPrefix predicate on the "subnet" field.
func SubnetHasPrefix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasPrefix(FieldSubnet, v))
}

// SubnetHasSuffix applies the HasSuffix predicate on the "subnet" field.
func SubnetHasSuffix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasSuffix(FieldSubnet, v))
}

// SubnetIsNil applies the IsNil predicate on the "subnet" field.
func SubnetIsNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIsNull(FieldSubnet))
}

// SubnetNotNil applies the NotNil predicate on the "subnet" field.
func SubnetNotNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotNull(FieldSubnet))
}

// SubnetEqualFold applies the EqualFold predicate on the "subnet" field.
func SubnetEqualFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEqualFold(FieldSubnet, v))
}

// SubnetContainsFold applies the ContainsFold predicate on the "subnet" field.
func SubnetContainsFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContainsFold(FieldSubnet, v))
}

// GatewayEQ applies the EQ predicate on the "gateway" field.
func GatewayEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldGateway, v))
}

// GatewayNEQ applies the NEQ predicate on the "gateway" field.
func GatewayNEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldGateway, v))
}

// GatewayIn applies the In predicate on the "gateway" field.
func GatewayIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldGateway, vs...))
}

// GatewayNotIn applies the NotIn predicate on the "gateway" field.
func GatewayNotIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldGateway, vs...))
}

// GatewayGT applies the GT predicate on the "gateway" field.
func GatewayGT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldGateway, v))
}

// GatewayGTE applies the GTE predicate on the "gateway" field.
func GatewayGTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldGateway, v))
}

// GatewayLT applies the LT predicate on the "gateway" field.
func GatewayLT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldGateway, v))
}

// GatewayLTE applies the LTE predicate on the "gateway" field.
func GatewayLTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldGateway, v))
}

// GatewayContains applies the Contains predicate on the "gateway" field.
func GatewayContains(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContains(FieldGateway, v))
}

// GatewayHasPrefix applies the HasPrefix predicate on the "gateway" field.
func GatewayHasPrefix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasPrefix(FieldGateway, v))
}

// GatewayHasSuffix applies the HasSuffix predicate on the "gateway" field.
func GatewayHasSuffix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasSuffix(FieldGateway, v))
}

// GatewayIsNil applies the IsNil predicate on the "gateway" field.
func GatewayIsNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIsNull(FieldGateway))
}

// GatewayNotNil applies the NotNil predicate on the "gateway" field.
func GatewayNotNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotNull(FieldGateway))
}

// GatewayEqualFold applies the EqualFold predicate on the "gateway" field.
func GatewayEqualFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEqualFold(FieldGateway, v))
}

// GatewayContainsFold applies the ContainsFold predicate on the "gateway" field.
func GatewayContainsFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContainsFold(FieldGateway, v))
}

// IPTypeEQ applies the EQ predicate on the "ip_type" field.
func IPTypeEQ(v IPType) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldIPType, v))
}

// IPTypeNEQ applies the NEQ predicate on the "ip_type" field.
func IPTypeNEQ(v IPType) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldIPType, v))
}

// IPTypeIn applies the In predicate on the "ip_type" field.
func IPTypeIn(vs ...IPType) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldIPType, vs...))
}

// IPTypeNotIn applies the NotIn predicate on the "ip_type" field.
func IPTypeNotIn(vs ...IPType) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldIPType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldStatus, vs...))
}

// VlanEQ applies the EQ predicate on the "vlan" field.
func VlanEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldVlan, v))
}

// VlanNEQ applies the NEQ predicate on the "vlan" field.
func VlanNEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldVlan, v))
}

// VlanIn applies the In predicate on the "vlan" field.
func VlanIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldVlan, vs...))
}

// VlanNotIn applies the NotIn predicate on the "vlan" field.
func VlanNotIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldVlan, vs...))
}

// VlanGT applies the GT predicate on the "vlan" field.
func VlanGT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldVlan, v))
}

// VlanGTE applies the GTE predicate on the "vlan" field.
func VlanGTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldVlan, v))
}

// VlanLT applies the LT predicate on the "vlan" field.
func VlanLT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldVlan, v))
}

// VlanLTE applies the LTE predicate on the "vlan" field.
func VlanLTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldVlan, v))
}

// VlanContains applies the Contains predicate on the "vlan" field.
func VlanContains(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContains(FieldVlan, v))
}

// VlanHasPrefix applies the HasPrefix predicate on the "vlan" field.
func VlanHasPrefix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasPrefix(FieldVlan, v))
}

// VlanHasSuffix applies the HasSuffix predicate on the "vlan" field.
func VlanHasSuffix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasSuffix(FieldVlan, v))
}

// VlanIsNil applies the IsNil predicate on the "vlan" field.
func VlanIsNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIsNull(FieldVlan))
}

// VlanNotNil applies the NotNil predicate on the "vlan" field.
func VlanNotNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotNull(FieldVlan))
}

// VlanEqualFold applies the EqualFold predicate on the "vlan" field.
func VlanEqualFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEqualFold(FieldVlan, v))
}

// VlanContainsFold applies the ContainsFold predicate on the "vlan" field.
func VlanContainsFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContainsFold(FieldVlan, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContainsFold(FieldNotes, v))
}

// AllocatedAtEQ applies the EQ predicate on the "allocated_at" field.
func AllocatedAtEQ(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldAllocatedAt, v))
}

// AllocatedAtNEQ applies the NEQ predicate on the "allocated_at" field.
func AllocatedAtNEQ(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldAllocatedAt, v))
}

// AllocatedAtIn applies the In predicate on the "allocated_at" field.
func AllocatedAtIn(vs ...time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldAllocatedAt, vs...))
}

// AllocatedAtNotIn applies the NotIn predicate on the "allocated_at" field.
func AllocatedAtNotIn(vs ...time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldAllocatedAt, vs...))
}

// AllocatedAtGT applies the GT predicate on the "allocated_at" field.
func AllocatedAtGT(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldAllocatedAt, v))
}

// AllocatedAtGTE applies the GTE predicate on the "allocated_at" field.
func AllocatedAtGTE(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldAllocatedAt, v))
}

// AllocatedAtLT applies the LT predicate on the "allocated_at" field.
func AllocatedAtLT(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldAllocatedAt, v))
}

// AllocatedAtLTE applies the LTE predicate on the "allocated_at" field.
func AllocatedAtLTE(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldAllocatedAt, v))
}

// AllocatedAtIsNil applies the IsNil predicate on the "allocated_at" field.
func AllocatedAtIsNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIsNull(FieldAllocatedAt))
}

// AllocatedAtNotNil applies the NotNil predicate on the "allocated_at" field.
func AllocatedAtNotNil() predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotNull(FieldAllocatedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAsset applies the HasEdge predicate on the "asset" edge.
func HasAsset() predicate.IPAddress {
	return predicate.IPAddress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.Asset) predicate.IPAddress {
	return predicate.IPAddress(func(s *sql.Selector) {
		step := newAssetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IPAddress) predicate.IPAddress {
	return predicate.IPAddress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IPAddress) predicate.IPAddress {
	return predicate.IPAddress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IPAddress) predicate.IPAddress {
	return predicate.IPAddress(sql.NotPredicates(p))
}
