// Code generated by ent, DO NOT EDIT.

package approvalnode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/your-org/atlas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLTE(FieldID, id))
}

// NodeOrder applies equality check predicate on the "node_order" field. It's identical to NodeOrderEQ.
func NodeOrder(v int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldNodeOrder, v))
}

// ApproverName applies equality check predicate on the "approver_name" field. It's identical to ApproverNameEQ.
func ApproverName(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldApproverName, v))
}

// ApproverEmail applies equality check predicate on the "approver_email" field. It's identical to ApproverEmailEQ.
func ApproverEmail(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldApproverEmail, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldComment, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldApprovedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldCreatedAt, v))
}

// NodeOrderEQ applies the EQ predicate on the "node_order" field.
func NodeOrderEQ(v int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldNodeOrder, v))
}

// NodeOrderNEQ applies the NEQ predicate on the "node_order" field.
func NodeOrderNEQ(v int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldNodeOrder, v))
}

// NodeOrderIn applies the In predicate on the "node_order" field.
func NodeOrderIn(vs ...int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldNodeOrder, vs...))
}

// NodeOrderNotIn applies the NotIn predicate on the "node_order" field.
func NodeOrderNotIn(vs ...int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldNodeOrder, vs...))
}

// NodeOrderGT applies the GT predicate on the "node_order" field.
func NodeOrderGT(v int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGT(FieldNodeOrder, v))
}

// NodeOrderGTE applies the GTE predicate on the "node_order" field.
func NodeOrderGTE(v int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGTE(FieldNodeOrder, v))
}

// NodeOrderLT applies the LT predicate on the "node_order" field.
func NodeOrderLT(v int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLT(FieldNodeOrder, v))
}

// NodeOrderLTE applies the LTE predicate on the "node_order" field.
func NodeOrderLTE(v int) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLTE(FieldNodeOrder, v))
}

// ApproverNameEQ applies the EQ predicate on the "approver_name" field.
func ApproverNameEQ(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldApproverName, v))
}

// ApproverNameNEQ applies the NEQ predicate on the "approver_name" field.
func ApproverNameNEQ(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldApproverName, v))
}

// ApproverNameIn applies the In predicate on the "approver_name" field.
func ApproverNameIn(vs ...string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldApproverName, vs...))
}

// ApproverNameNotIn applies the NotIn predicate on the "approver_name" field.
func ApproverNameNotIn(vs ...string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldApproverName, vs...))
}

// ApproverNameGT applies the GT predicate on the "approver_name" field.
func ApproverNameGT(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGT(FieldApproverName, v))
}

// ApproverNameGTE applies the GTE predicate on the "approver_name" field.
func ApproverNameGTE(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGTE(FieldApproverName, v))
}

// ApproverNameLT applies the LT predicate on the "approver_name" field.
func ApproverNameLT(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLT(FieldApproverName, v))
}

// ApproverNameLTE applies the LTE predicate on the "approver_name" field.
func ApproverNameLTE(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLTE(FieldApproverName, v))
}

// ApproverNameContains applies the Contains predicate on the "approver_name" field.
func ApproverNameContains(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldContains(FieldApproverName, v))
}

// ApproverNameHasPrefix applies the HasPrefix predicate on the "approver_name" field.
func ApproverNameHasPrefix(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldHasPrefix(FieldApproverName, v))
}

// ApproverNameHasSuffix applies the HasSuffix predicate on the "approver_name" field.
func ApproverNameHasSuffix(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldHasSuffix(FieldApproverName, v))
}

// ApproverNameEqualFold applies the EqualFold predicate on the "approver_name" field.
func ApproverNameEqualFold(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEqualFold(FieldApproverName, v))
}

// ApproverNameContainsFold applies the ContainsFold predicate on the "approver_name" field.
func ApproverNameContainsFold(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldContainsFold(FieldApproverName, v))
}

// ApproverEmailEQ applies the EQ predicate on the "approver_email" field.
func ApproverEmailEQ(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldApproverEmail, v))
}

// ApproverEmailNEQ applies the NEQ predicate on the "approver_email" field.
func ApproverEmailNEQ(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldApproverEmail, v))
}

// ApproverEmailIn applies the In predicate on the "approver_email" field.
func ApproverEmailIn(vs ...string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldApproverEmail, vs...))
}

// ApproverEmailNotIn applies the NotIn predicate on the "approver_email" field.
func ApproverEmailNotIn(vs ...string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldApproverEmail, vs...))
}

// ApproverEmailGT applies the GT predicate on the "approver_email" field.
func ApproverEmailGT(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGT(FieldApproverEmail, v))
}

// ApproverEmailGTE applies the GTE predicate on the "approver_email" field.
func ApproverEmailGTE(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGTE(FieldApproverEmail, v))
}

// ApproverEmailLT applies the LT predicate on the "approver_email" field.
func ApproverEmailLT(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLT(FieldApproverEmail, v))
}

// ApproverEmailLTE applies the LTE predicate on the "approver_email" field.
func ApproverEmailLTE(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLTE(FieldApproverEmail, v))
}

// ApproverEmailContains applies the Contains predicate on the "approver_email" field.
func ApproverEmailContains(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldContains(FieldApproverEmail, v))
}

// ApproverEmailHasPrefix applies the HasPrefix predicate on the "approver_email" field.
func ApproverEmailHasPrefix(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldHasPrefix(FieldApproverEmail, v))
}

// ApproverEmailHasSuffix applies the HasSuffix predicate on the "approver_email" field.
func ApproverEmailHasSuffix(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldHasSuffix(FieldApproverEmail, v))
}

// ApproverEmailIsNil applies the IsNil predicate on the "approver_email" field.
func ApproverEmailIsNil() predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIsNull(FieldApproverEmail))
}

// ApproverEmailNotNil applies the NotNil predicate on the "approver_email" field.
func ApproverEmailNotNil() predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotNull(FieldApproverEmail))
}

// ApproverEmailEqualFold applies the EqualFold predicate on the "approver_email" field.
func ApproverEmailEqualFold(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEqualFold(FieldApproverEmail, v))
}

// ApproverEmailContainsFold applies the ContainsFold predicate on the "approver_email" field.
func ApproverEmailContainsFold(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldContainsFold(FieldApproverEmail, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldStatus, vs...))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldHasSuffix(FieldComment, v))
}

// CommentIsNil applies the IsNil predicate on the "comment" field.
func CommentIsNil() predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIsNull(FieldComment))
}

// CommentNotNil applies the NotNil predicate on the "comment" field.
func CommentNotNil() predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotNull(FieldComment))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldContainsFold(FieldComment, v))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotNull(FieldApprovedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.FieldLTE(FieldCreatedAt, v))
}

// HasApproval applies the HasEdge predicate on the "approval" edge.
func HasApproval() predicate.ApprovalNode {
	return predicate.ApprovalNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ApprovalTable, ApprovalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApprovalWith applies the HasEdge predicate on the "approval" edge with a given conditions (other predicates).
func HasApprovalWith(preds ...predicate.Approval) predicate.ApprovalNode {
	return predicate.ApprovalNode(func(s *sql.Selector) {
		step := newApprovalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApprovalNode) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApprovalNode) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApprovalNode) predicate.ApprovalNode {
	return predicate.ApprovalNode(sql.NotPredicates(p))
}
